export const MOCK_TICKETS = [
    {
        ticketId: 'TCK1001',
        customerName: 'John Doe',
        issueType: 'Delivery',
        issueDescription: "It's been 12 hours and I still haven’t gotten my delivery, I’ve tried reaching out to the delivery rep but his number has been switched off. Please resolve this soon.",
        status: 'Open',
        priority: 'High',
        vendorName: 'TechGears Ltd',
        deliveryRep: 'Salami Ahmed',
        dateCreated: '25/01/27 10:15 AM',
        adminResponse: '',
        resolutionHistory: '',
    },
    {
        ticketId: 'TCK1002',
        customerName: 'Jane Smith',
        issueType: 'Technical',
        issueDescription: "App keeps crashing when I try to checkout.",
        status: 'In progress',
        priority: 'High',
        vendorName: 'Internal Tech',
        deliveryRep: 'N/A',
        dateCreated: '25/09/20 11:45 AM',
        adminResponse: 'We have escalated this to the development team for investigation.',
        resolutionHistory: 'Responded on 09/20.',
    },
    {
        ticketId: 'TCK1003',
        customerName: 'Alex Johnson',
        issueType: 'Billing',
        issueDescription: "I was overcharged on my last invoice.",
        status: 'Resolved',
        priority: 'Medium',
        vendorName: 'Finance Dept',
        deliveryRep: 'N/A',
        dateCreated: '25/09/15 03:00 PM',
        adminResponse: 'A full refund for the overcharged amount has been processed.',
        resolutionHistory: 'Responded on 09/16. Resolved on 09/17.',
    },
    // --- Extended Data (TCK1004 to TCK1009) ---
    {
        ticketId: 'TCK1004',
        customerName: 'Sarah Connor',
        issueType: 'Product Quality',
        issueDescription: "The item received was damaged and appears to have been used before.",
        status: 'Open',
        priority: 'High',
        vendorName: 'Global Supplies',
        deliveryRep: 'Maria Benitez',
        dateCreated: '25/10/01 09:00 AM',
        adminResponse: '',
        resolutionHistory: '',
    },
    {
        ticketId: 'TCK1005',
        customerName: 'Michael Brown',
        issueType: 'General Inquiry',
        issueDescription: "Can I cancel my pending order? I made a mistake on the delivery address.",
        status: 'Resolved',
        priority: 'Low',
        vendorName: 'Customer Service',
        deliveryRep: 'N/A',
        dateCreated: '25/09/28 02:30 PM',
        adminResponse: 'The order was successfully cancelled and a confirmation email was sent.',
        resolutionHistory: 'Responded on 09/28. Resolved on 09/28.',
    },
    {
        ticketId: 'TCK1006',
        customerName: 'Emily Clark',
        issueType: 'Delivery',
        issueDescription: "The tracking information hasn't updated in three days. I need an ETA.",
        status: 'In progress',
        priority: 'Medium',
        vendorName: 'Swift Logistics',
        deliveryRep: 'David Lee',
        dateCreated: '25/09/25 11:00 AM',
        adminResponse: 'We are contacting the courier for an immediate status update and will get back to you within 2 hours.',
        resolutionHistory: 'Responded on 09/25.',
    },
    {
        ticketId: 'TCK1007',
        customerName: 'Tom Harris',
        issueType: 'Technical',
        issueDescription: "The password reset link is not working.",
        status: 'Open',
        priority: 'Medium',
        vendorName: 'Internal Tech',
        deliveryRep: 'N/A',
        dateCreated: '25/10/02 01:10 PM',
        adminResponse: '',
        resolutionHistory: '',
    },
    {
        ticketId: 'TCK1008',
        customerName: 'Laura White',
        issueType: 'Billing',
        issueDescription: "I haven't received my refund 5 days after cancellation.",
        status: 'In progress',
        priority: 'High',
        vendorName: 'Finance Dept',
        deliveryRep: 'N/A',
        dateCreated: '25/09/22 04:45 PM',
        adminResponse: 'We have expedited the refund. It should reflect in your account within 24 hours.',
        resolutionHistory: 'Responded on 09/23.',
    },
    {
        ticketId: 'TCK1009',
        customerName: 'Peter Green',
        issueType: 'Product Quality',
        issueDescription: "The color of the product I received is wrong.",
        status: 'Open',
        priority: 'Low',
        vendorName: 'ColorTech Inc.',
        deliveryRep: 'Sarah Jones',
        dateCreated: '25/10/02 08:30 AM',
        adminResponse: '',
        resolutionHistory: '',
    },
];