export const vendorData = [
  {
    id: "VND-482903",
    name: "Maxwell Global Ltd",
    businessType: "Gas Refill Service",
    withdrawalDate: "March 26, 2025",
    withdrawalAmount: "₦3,200,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "UBA",
    accountNumber: "6758392101",
    country: "Nigeria",
    ipAddress: "197.210.45.123",
    deviceBrowser: "Windows 10 - Chrome 120.0",
    status: "Pending Review",
    riskScore: "High Risk - 92%",
    timestamp: "March 26, 2025 | 10:15 AM",
    flaggedReasons: [
      "Unusual withdrawal frequency (5+ large withdrawals in 24 hours)",
      "New receiving bank account not previously used",
      "Large increase in withdrawal amounts (+300% compared to last 7 days)",
    ],
    suspiciousIndicators: [
      "First-time withdrawal to this account",
      "Multiple failed login attempts before withdrawal request",
      "Matching transaction pattern to previous fraudulent cases",
      "Geographic IP mismatch (Lagos, Nigeria → Withdrawn to UBA, Port Harcourt)",
    ],
    previousFraudAlerts: [
      "Suspicious vendor flagged last month for unusual refund requests",
      "One customer previously reported non-receipt of goods",
    ],
    transactionHistory: [
      { date: "25/03/2025", amount: "2,500,000", bank: "GTBank", status: "Completed" },
      { date: "25/03/2025", amount: "1,150,000", bank: "Zenith Bank", status: "Completed" },
      { date: "24/03/2025", amount: "3,750,000", bank: "UBA", status: "Flagged" },
      { date: "24/03/2025", amount: "850,000", bank: "First Bank", status: "Flagged" },
      { date: "23/03/2025", amount: "4,200,000", bank: "Access Bank", status: "Confirmed Fraud" },
    ],
    adminNotes: "Vendor was flagged last month for chargebacks. Investigate further.",
    reviewer: "Admin John Doe",
    lastUpdate: "March 26, 2025 | 11:30 AM",
  },
  {
    id: "VND-482904",
    name: "Elite Traders NG",
    businessType: "Electronics Sales",
    withdrawalDate: "March 25, 2025",
    withdrawalAmount: "₦4,800,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "Zenith Bank",
    accountNumber: "8749301265",
    country: "Ghana",
    ipAddress: "41.220.10.55",
    deviceBrowser: "MacOS - Safari 17.1",
    status: "Confirmed Fraud",
    riskScore: "Critical Risk - 96%",
    timestamp: "March 25, 2025 | 03:20 PM",
    flaggedReasons: [
      "Multiple chargebacks initiated by customers in the last 48 hours",
      "IP address from high-risk country (Ghana)",
      "Velocity of sales is highly inconsistent with business profile",
    ],
    suspiciousIndicators: [
      "Account opened less than 30 days ago",
      "Previous successful withdrawals were significantly smaller",
      "Matching device fingerprint with known fraudsters",
    ],
    previousFraudAlerts: [
      "Vendor blacklisted on a different platform 6 months ago (Name match)",
      "High volume of failed transactions prior to successful one",
    ],
    transactionHistory: [
      { date: "24/03/2025", amount: "950,000", bank: "Fidelity Bank", status: "Completed" },
      { date: "23/03/2025", amount: "700,000", bank: "Access Bank", status: "Completed" },
      { date: "22/03/2025", amount: "2,100,000", bank: "Zenith Bank", status: "Flagged" },
      { date: "21/03/2025", amount: "450,000", bank: "GTBank", status: "Completed" },
      { date: "20/03/2025", amount: "1,500,000", bank: "UBA", status: "Completed" },
    ],
    adminNotes: "Immediate funds freeze. Coordinate with compliance for blacklisting. Confirmed link to 'Operation Silent'.",
    reviewer: "Admin Jane Smith",
    lastUpdate: "March 26, 2025 | 09:00 AM",
  },
  {
    id: "VND-482905",
    name: "Jide Enterprises",
    businessType: "Agro Commodities",
    withdrawalDate: "March 23, 2025",
    withdrawalAmount: "₦2,750,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "First Bank",
    accountNumber: "1938754620",
    country: "Nigeria",
    ipAddress: "105.112.18.99",
    deviceBrowser: "Android - Firefox 90.0",
    status: "Under Investigation",
    riskScore: "High Risk - 88%",
    timestamp: "March 23, 2025 | 07:45 AM",
    flaggedReasons: [
      "Withdrawal amount is exactly the limit threshold for this vendor tier",
      "First withdrawal after a 60-day period of inactivity",
      "Linked to a compromised vendor account in the past",
    ],
    suspiciousIndicators: [
      "Transaction initiated outside of regular business hours (Sunday morning)",
      "IP address is a known proxy/VPN service",
      "Change in primary contact email before the withdrawal",
    ],
    previousFraudAlerts: [
      "None",
    ],
    transactionHistory: [
      { date: "20/01/2025", amount: "1,500,000", bank: "First Bank", status: "Completed" },
      { date: "15/01/2025", amount: "900,000", bank: "Access Bank", status: "Completed" },
      { date: "10/01/2025", amount: "2,000,000", bank: "GTBank", status: "Completed" },
      { date: "05/01/2025", amount: "1,250,000", bank: "UBA", status: "Completed" },
      { date: "01/01/2025", amount: "600,000", bank: "Zenith Bank", status: "Completed" },
    ],
    adminNotes: "Wait for account owner verification call. Funds frozen pending confirmation. Possible account takeover.",
    reviewer: "Admin John Doe",
    lastUpdate: "March 25, 2025 | 11:00 AM",
  },
  {
    id: "VND-482906",
    name: "Maxwell Global Ltd",
    businessType: "Logistics",
    withdrawalDate: "March 23, 2025",
    withdrawalAmount: "₦1,150,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "GTBank",
    accountNumber: "3987610245",
    country: "Nigeria",
    ipAddress: "154.66.201.33",
    deviceBrowser: "iPhone 14 - Mobile App",
    status: "Pending Review",
    riskScore: "Medium Risk - 75%",
    timestamp: "March 23, 2025 | 09:10 PM",
    flaggedReasons: [
      "Low balance in the source account before the withdrawal request",
    ],
    suspiciousIndicators: [
      "Change in device type used for transaction (Switched from Android to iOS)",
    ],
    previousFraudAlerts: [
      "None",
    ],
    transactionHistory: [
      { date: "22/03/2025", amount: "500,000", bank: "First Bank", status: "Completed" },
      { date: "21/03/2025", amount: "750,000", bank: "Access Bank", status: "Completed" },
      { date: "20/03/2025", amount: "300,000", bank: "GTBank", status: "Completed" },
      { date: "19/03/2025", amount: "1,000,000", bank: "UBA", status: "Completed" },
      { date: "18/03/2025", amount: "1,200,000", bank: "Zenith Bank", status: "Completed" },
    ],
    adminNotes: "Standard review for low-score flag. Proceed if no other alerts are present. Possible false positive.",
    reviewer: "Admin Ken Obi",
    lastUpdate: "March 24, 2025 | 08:00 AM",
  },
  {
    id: "VND-482907",
    name: "Alpha Merchants",
    businessType: "Online Education",
    withdrawalDate: "March 22, 2025",
    withdrawalAmount: "₦3,900,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "Access Bank",
    accountNumber: "7654329871",
    country: "Nigeria",
    ipAddress: "197.210.150.1",
    deviceBrowser: "Linux - Opera 80.0",
    status: "Confirmed Fraud",
    riskScore: "Critical Risk - 98%",
    timestamp: "March 22, 2025 | 11:30 AM",
    flaggedReasons: [
      "Immediate withdrawal of a large deposit (Deposit-Withdrawal cycle < 1 hour)",
      "Known bank account number associated with money laundering",
    ],
    suspiciousIndicators: [
      "Transaction initiated from a highly unusual browser (Opera on Linux)",
      "Vendor's registration details are incomplete",
    ],
    previousFraudAlerts: [
      "Vendor reported by a bank partner for suspicious activities last week",
    ],
    transactionHistory: [
      { date: "22/03/2025", amount: "5,000,000", bank: "First Bank", status: "Pending" },
      { date: "21/03/2025", amount: "1,500,000", bank: "Access Bank", status: "Completed" },
      { date: "20/03/2025", amount: "2,000,000", bank: "GTBank", status: "Completed" },
      { date: "19/03/2025", amount: "1,100,000", bank: "UBA", status: "Completed" },
      { date: "18/03/2025", amount: "800,000", bank: "Zenith Bank", status: "Completed" },
    ],
    adminNotes: "Blacklist account and IP immediately. Alert police. This is a repeat offender using a new vendor profile.",
    reviewer: "Admin Jane Smith",
    lastUpdate: "March 22, 2025 | 01:00 PM",
  },
  {
    id: "VND-482908",
    name: "Oasis Ventures",
    businessType: "Travel Agency",
    withdrawalDate: "March 21, 2025",
    withdrawalAmount: "₦850,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "UBA",
    accountNumber: "1456789234",
    country: "Nigeria",
    ipAddress: "41.203.25.77",
    deviceBrowser: "Windows 10 - Edge 100.0",
    status: "Under Investigation",
    riskScore: "Medium Risk - 78%",
    timestamp: "March 21, 2025 | 04:55 PM",
    flaggedReasons: [
      "Withdrawal pattern shift from daily to weekly",
      "Account used for non-standard transactions (P2P instead of B2C)",
    ],
    suspiciousIndicators: [
      "Transaction value is an exact round number, which is unusual for this business",
    ],
    previousFraudAlerts: [
      "None",
    ],
    transactionHistory: [
      { date: "14/03/2025", amount: "700,000", bank: "First Bank", status: "Completed" },
      { date: "07/03/2025", amount: "900,000", bank: "Access Bank", status: "Completed" },
      { date: "01/03/2025", amount: "800,000", bank: "GTBank", status: "Completed" },
      { date: "22/02/2025", amount: "1,000,000", bank: "UBA", status: "Completed" },
      { date: "15/02/2025", amount: "1,100,000", bank: "Zenith Bank", status: "Completed" },
    ],
    adminNotes: "Contact vendor to confirm purpose of withdrawal. Low score, but pattern is odd. Hold for 24 hours.",
    reviewer: "Admin Ken Obi",
    lastUpdate: "March 22, 2025 | 09:30 AM",
  },
  {
    id: "VND-482909",
    name: "United Agro Services",
    businessType: "Farming Tools",
    withdrawalDate: "March 20, 2025",
    withdrawalAmount: "₦1,980,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "First Bank",
    accountNumber: "2345678912",
    country: "Nigeria",
    ipAddress: "197.210.12.5",
    deviceBrowser: "Windows 11 - Chrome 121.0",
    status: "Pending Review",
    riskScore: "Medium Risk - 70%",
    timestamp: "March 20, 2025 | 08:20 AM",
    flaggedReasons: [
      "Withdrawal amount is slightly higher than the average for this vendor",
    ],
    suspiciousIndicators: [
      "None",
    ],
    previousFraudAlerts: [
      "None",
    ],
    transactionHistory: [
      { date: "19/03/2025", amount: "1,500,000", bank: "First Bank", status: "Completed" },
      { date: "18/03/2025", amount: "1,750,000", bank: "Access Bank", status: "Completed" },
      { date: "17/03/2025", amount: "1,600,000", bank: "GTBank", status: "Completed" },
      { date: "16/03/2025", amount: "1,800,000", bank: "UBA", status: "Completed" },
      { date: "15/03/2025", amount: "1,900,000", bank: "Zenith Bank", status: "Completed" },
    ],
    adminNotes: "Approve after 1 hour hold. Low risk, likely a normal business transaction.",
    reviewer: "Admin John Doe",
    lastUpdate: "March 20, 2025 | 09:20 AM",
  },
  {
    id: "VND-482910",
    name: "Rapid Logistics Ltd",
    businessType: "Haulage and Delivery",
    withdrawalDate: "March 19, 2025",
    withdrawalAmount: "₦5,250,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "Zenith Bank",
    accountNumber: "6543210987",
    country: "Nigeria",
    ipAddress: "154.120.5.18",
    deviceBrowser: "MacOS - Firefox 123.0",
    status: "Confirmed Fraud",
    riskScore: "Critical Risk - 95%",
    timestamp: "March 19, 2025 | 02:10 PM",
    flaggedReasons: [
      "Attempt to withdraw the maximum allowed daily limit",
      "Receiving account is a newly registered individual account, not a corporate one",
      "Multiple IP addresses used for the same session",
    ],
    suspiciousIndicators: [
      "User session duration was less than 3 minutes (Too fast for a manual process)",
      "High-value transactions with no corresponding sales records found",
    ],
    previousFraudAlerts: [
      "Previous successful withdrawal was immediately followed by a customer chargeback",
    ],
    transactionHistory: [
      { date: "18/03/2025", amount: "1,000,000", bank: "First Bank", status: "Completed" },
      { date: "17/03/2025", amount: "2,000,000", bank: "Access Bank", status: "Completed" },
      { date: "16/03/2025", amount: "1,500,000", bank: "GTBank", status: "Flagged" },
      { date: "15/03/2025", amount: "3,000,000", bank: "UBA", status: "Completed" },
      { date: "14/03/2025", amount: "2,500,000", bank: "Zenith Bank", status: "Completed" },
    ],
    adminNotes: "Confirmed vendor account was hijacked. Blacklist receiving account and freeze all remaining funds.",
    reviewer: "Admin Jane Smith",
    lastUpdate: "March 20, 2025 | 08:30 AM",
  },
  {
    id: "VND-482911",
    name: "Evergreen Stores",
    businessType: "General Merchandise",
    withdrawalDate: "March 18, 2025",
    withdrawalAmount: "₦690,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "GTBank",
    accountNumber: "6789345123",
    country: "Benin",
    ipAddress: "102.89.20.1",
    deviceBrowser: "Android - Chrome 122.0",
    status: "Confirmed Fraud",
    riskScore: "High Risk - 89%",
    timestamp: "March 18, 2025 | 05:00 AM",
    flaggedReasons: [
      "Geographic IP mismatch (Benin → Nigerian Bank)",
      "Withdrawal initiated at a highly unusual time (5 AM local time)",
    ],
    suspiciousIndicators: [
      "Vendor name has been changed twice in the last month",
      "Transaction completed without two-factor authentication (2FA bypass)",
    ],
    previousFraudAlerts: [
      "None",
    ],
    transactionHistory: [
      { date: "17/03/2025", amount: "500,000", bank: "First Bank", status: "Completed" },
      { date: "16/03/2025", amount: "400,000", bank: "Access Bank", status: "Completed" },
      { date: "15/03/2025", amount: "300,000", bank: "GTBank", status: "Completed" },
      { date: "14/03/2025", amount: "200,000", bank: "UBA", status: "Completed" },
      { date: "13/03/2025", amount: "100,000", bank: "Zenith Bank", status: "Completed" },
    ],
    adminNotes: "Confirm with GTBank to freeze funds. Strong indicators of international fraud. Blacklist.",
    reviewer: "Admin Ken Obi",
    lastUpdate: "March 18, 2025 | 10:00 AM",
  },
  {
    id: "VND-482912",
    name: "Dynamic Exporters",
    businessType: "Textile & Fabric",
    withdrawalDate: "March 17, 2025",
    withdrawalAmount: "₦3,750,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "Access Bank",
    accountNumber: "1234987650",
    country: "Nigeria",
    ipAddress: "197.210.15.22",
    deviceBrowser: "iPad Pro - Safari 17.0",
    status: "Pending Review",
    riskScore: "High Risk - 82%",
    timestamp: "March 17, 2025 | 06:40 PM",
    flaggedReasons: [
      "Multiple large withdrawals to different bank accounts in a short period",
      "Vendor's trading volume dropped significantly before the withdrawal",
    ],
    suspiciousIndicators: [
      "Receiving account is a microfinance bank account (Unusual for this business)",
    ],
    previousFraudAlerts: [
      "Vendor's login credentials were found on a dark web forum (reported 2 months ago)",
    ],
    transactionHistory: [
      { date: "16/03/2025", amount: "1,500,000", bank: "First Bank", status: "Completed" },
      { date: "15/03/2025", amount: "2,000,000", bank: "Zenith Bank", status: "Completed" },
      { date: "14/03/2025", amount: "1,800,000", bank: "UBA", status: "Completed" },
      { date: "13/03/2025", amount: "1,900,000", bank: "GTBank", status: "Completed" },
      { date: "12/03/2025", amount: "2,100,000", bank: "Access Bank", status: "Completed" },
    ],
    adminNotes: "Place a temporary hold. Need to contact the vendor's corporate phone number for confirmation of transaction intent.",
    reviewer: "Admin John Doe",
    lastUpdate: "March 18, 2025 | 09:00 AM",
  },
  {
    id: "VND-482913",
    name: "NextGen Dealers",
    businessType: "Automotive Parts",
    withdrawalDate: "March 16, 2025",
    withdrawalAmount: "₦2,680,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "UBA",
    accountNumber: "8901234567",
    country: "Nigeria",
    ipAddress: "102.88.50.11",
    deviceBrowser: "Windows 10 - Chrome 120.0",
    status: "Pending Review",
    riskScore: "Critical Risk - 97%",
    timestamp: "March 16, 2025 | 09:30 AM",
    flaggedReasons: [
      "Extremely high-risk score, automatically flagged for immediate manual review",
      "Account linked to 3 other confirmed fraudulent vendors via shared bank account",
      "Withdrawal initiated immediately after a password reset",
    ],
    suspiciousIndicators: [
      "Mismatch in the name on the bank account and the vendor name",
    ],
    previousFraudAlerts: [
      "Vendor was under investigation 3 months ago for suspicious customer complaints (Insufficient evidence to blacklist)",
    ],
    transactionHistory: [
      { date: "15/03/2025", amount: "1,500,000", bank: "First Bank", status: "Completed" },
      { date: "14/03/2025", amount: "1,700,000", bank: "Zenith Bank", status: "Completed" },
      { date: "13/03/2025", amount: "1,800,000", bank: "UBA", status: "Completed" },
      { date: "12/03/2025", amount: "1,900,000", bank: "GTBank", status: "Completed" },
      { date: "11/03/2025", amount: "2,000,000", bank: "Access Bank", status: "Completed" },
    ],
    adminNotes: "Lock vendor account access and freeze funds. Contact UBA immediately. **HIGH PRIORITY FRAUD.**",
    reviewer: "Admin Jane Smith",
    lastUpdate: "March 16, 2025 | 10:30 AM",
  },
  {
    id: "VND-482914",
    name: "Fresh Food Distrib",
    businessType: "Perishable Goods",
    withdrawalDate: "March 15, 2025",
    withdrawalAmount: "₦720,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "First Bank",
    accountNumber: "1098765432",
    country: "Nigeria",
    ipAddress: "197.210.100.44",
    deviceBrowser: "Android - Mobile App",
    status: "Under Investigation",
    riskScore: "Medium Risk - 71%",
    timestamp: "March 15, 2025 | 01:45 PM",
    flaggedReasons: [
      "Withdrawal is slightly below the minimum average for this vendor",
    ],
    suspiciousIndicators: [
      "None",
    ],
    previousFraudAlerts: [
      "None",
    ],
    transactionHistory: [
      { date: "14/03/2025", amount: "800,000", bank: "First Bank", status: "Completed" },
      { date: "13/03/2025", amount: "900,000", bank: "Zenith Bank", status: "Completed" },
      { date: "12/03/2025", amount: "1,000,000", bank: "UBA", status: "Completed" },
      { date: "11/03/2025", amount: "1,100,000", bank: "GTBank", status: "Completed" },
      { date: "10/03/2025", amount: "1,200,000", bank: "Access Bank", status: "Completed" },
    ],
    adminNotes: "Wait for the end of the day. If no other alerts, approve. Standard low-risk anomaly.",
    reviewer: "Admin Ken Obi",
    lastUpdate: "March 15, 2025 | 04:00 PM",
  },
  {
    id: "VND-482915",
    name: "GreenMart Ltd",
    businessType: "Retail Superstore",
    withdrawalDate: "March 14, 2025",
    withdrawalAmount: "₦5,000,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "Zenith Bank",
    accountNumber: "2109876543",
    country: "Nigeria",
    ipAddress: "197.210.200.70",
    deviceBrowser: "Windows 10 - Edge 105.0",
    status: "Confirmed Fraud",
    riskScore: "High Risk - 91%",
    timestamp: "March 14, 2025 | 08:50 PM",
    flaggedReasons: [
      "Immediate full withdrawal of all cleared funds on the platform",
      "Account details are registered as an individual but the business name suggests corporate",
    ],
    suspiciousIndicators: [
      "Vendor has been inactive for 9 months, then suddenly initiated high-value transactions",
    ],
    previousFraudAlerts: [
      "Vendor failed KYC verification 4 months ago and was temporarily suspended",
    ],
    transactionHistory: [
      { date: "13/03/2025", amount: "1,500,000", bank: "First Bank", status: "Completed" },
      { date: "12/03/2025", amount: "1,700,000", bank: "Access Bank", status: "Completed" },
      { date: "11/03/2025", amount: "1,800,000", bank: "GTBank", status: "Completed" },
      { date: "10/03/2025", amount: "1,900,000", bank: "UBA", status: "Completed" },
      { date: "09/03/2025", amount: "2,000,000", bank: "Zenith Bank", status: "Completed" },
    ],
    adminNotes: "Confirmed vendor's corporate registration is fake. Freeze funds and report to financial intelligence unit.",
    reviewer: "Admin Jane Smith",
    lastUpdate: "March 15, 2025 | 10:00 AM",
  },
  {
    id: "VND-482916",
    name: "Smart Tech Ventures",
    businessType: "IT Services",
    withdrawalDate: "March 13, 2025",
    withdrawalAmount: "₦1,150,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "GTBank",
    accountNumber: "7658493012",
    country: "Nigeria",
    ipAddress: "41.203.200.15",
    deviceBrowser: "Windows 11 - Firefox 124.0",
    status: "Confirmed Fraud",
    riskScore: "Medium Risk - 79%",
    timestamp: "March 13, 2025 | 02:20 PM",
    flaggedReasons: [
      "Withdrawal to an account that has been blacklisted for another vendor",
    ],
    suspiciousIndicators: [
      "Vendor attempted to split a large withdrawal into multiple smaller ones (Smurfing pattern)",
    ],
    previousFraudAlerts: [
      "None",
    ],
    transactionHistory: [
      { date: "12/03/2025", amount: "500,000", bank: "First Bank", status: "Completed" },
      { date: "11/03/2025", amount: "400,000", bank: "Access Bank", status: "Completed" },
      { date: "10/03/2025", amount: "300,000", bank: "GTBank", status: "Completed" },
      { date: "09/03/2025", amount: "200,000", bank: "UBA", status: "Completed" },
      { date: "08/03/2025", amount: "100,000", bank: "Zenith Bank", status: "Completed" },
    ],
    adminNotes: "Confirm receiving bank account blacklist status. If confirmed, change status to Confirmed Fraud and action Blacklist.",
    reviewer: "Admin John Doe",
    lastUpdate: "March 13, 2025 | 03:30 PM",
  },
  {
    id: "VND-482917",
    name: "Empire Solutions",
    businessType: "Consulting",
    withdrawalDate: "March 12, 2025",
    withdrawalAmount: "₦2,850,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "Access Bank",
    accountNumber: "4509231678",
    country: "Nigeria",
    ipAddress: "197.210.1.10",
    deviceBrowser: "MacBook Pro - Chrome 120.0",
    status: "Pending Review",
    riskScore: "High Risk - 85%",
    timestamp: "March 12, 2025 | 11:00 AM",
    flaggedReasons: [
      "Inconsistent location history for the user's login and withdrawal",
      "High-value withdrawal is unusually early in the month (compared to end-of-month pattern)",
    ],
    suspiciousIndicators: [
      "None",
    ],
    previousFraudAlerts: [
      "None",
    ],
    transactionHistory: [
      { date: "11/03/2025", amount: "3,000,000", bank: "First Bank", status: "Completed" },
      { date: "10/03/2025", amount: "3,500,000", bank: "Zenith Bank", status: "Completed" },
      { date: "09/03/2025", amount: "4,000,000", bank: "UBA", status: "Completed" },
      { date: "08/03/2025", amount: "4,500,000", bank: "GTBank", status: "Completed" },
      { date: "07/03/2025", amount: "5,000,000", bank: "Access Bank", status: "Completed" },
    ],
    adminNotes: "Manual geo-location check required. If location is confirmed, proceed with approval. Otherwise, place a hold.",
    reviewer: "Admin Ken Obi",
    lastUpdate: "March 12, 2025 | 01:00 PM",
  },
  {
    id: "VND-482918",
    name: "Tech Hub Integrators",
    businessType: "Software Development",
    withdrawalDate: "March 11, 2025",
    withdrawalAmount: "₦4,100,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "First Bank",
    accountNumber: "9901123456",
    country: "Nigeria",
    ipAddress: "154.66.5.90",
    deviceBrowser: "Linux - Chrome 119.0",
    status: "Pending Review",
    riskScore: "Medium Risk - 73%",
    timestamp: "March 11, 2025 | 04:30 PM",
    flaggedReasons: [
      "Large withdrawal after a period of small, low-risk transactions",
    ],
    suspiciousIndicators: [
      "Device browser is unusual for a corporate account (Linux)",
      "First withdrawal in 90 days",
    ],
    previousFraudAlerts: [
      "None",
    ],
    transactionHistory: [
      { date: "01/03/2025", amount: "500,000", bank: "First Bank", status: "Completed" },
      { date: "01/02/2025", amount: "600,000", bank: "Zenith Bank", status: "Completed" },
      { date: "01/01/2025", amount: "700,000", bank: "UBA", status: "Completed" },
      { date: "01/12/2024", amount: "800,000", bank: "GTBank", status: "Completed" },
      { date: "01/11/2024", amount: "900,000", bank: "Access Bank", status: "Completed" },
    ],
    adminNotes: "Contact the vendor via registered phone number for transaction verification. Hold for 48 hours.",
    reviewer: "Admin John Doe",
    lastUpdate: "March 12, 2025 | 09:00 AM",
  },
];
export const transactionData = [
  // --- Original Data (TXN-20250304) ---
  {
    id: "TXN-20250304",
    vendorName: "Maxwell Global Ltd",
    vendorId: "VND-482903",
    businessType: "Gas Refill Service",
    withdrawalRequestDate: "March 26, 2025",
    withdrawalAmount: "₦3,200,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "UBA",
    accountNumber: "6758392101",
    receivingCountry: "Nigeria",
    ipAddress: "197.210.45.123",
    deviceBrowser: "Windows 10 - Chrome 120.0",
    paymentStatus: "Successful",
    fraudRiskScore: 87,
    riskLevel: "High Risk",
    flaggedBy: "Automated Fraud Detection System",
    flagReason: "Unusual Login Location",
    adminAssigned: "John Doe (Fraud Analyst)",
    status: "Under Investigation",
    transactionHistory: [
      { id: 'TXN-20250303', date: '03/03/2025', amount: '150,000', method: 'Mastercard', location: 'Lagos, Nigeria 🇳🇬', status: 'Completed' },
      { id: 'TXN-20250302', date: '02/03/2025', amount: '85,000', method: 'Visa Card', location: 'Lagos, Nigeria 🇳🇬', status: 'Completed' },
      { id: 'TXN-20250301', date: '01/03/2025', amount: '105,000', method: 'Bank Transfer', location: 'Lagos, Nigeria 🇳🇬', status: 'Completed' },
      { id: 'TXN-20250228', date: '28/02/2025', amount: '98,000', method: 'Visa Card', location: 'Lagos, Nigeria 🇳🇬', status: 'Completed' },
      { id: 'TXN-20250227', date: '27/02/2025', amount: '950,000', method: 'Visa Card', location: 'Nairobi, Kenya 🇰🇪', status: 'Flagged' },
    ],
    relatedActivities: [
      { date: '02/02/2025', activity: 'Multiple failed login attempts from different locations', status: 'Completed' },
      { date: '14/02/2025', activity: 'Attempted withdrawal flagged for unusual frequency', status: 'Completed' },
      { date: '25/02/2025', activity: 'Chargeback request on a large order', status: 'Completed' },
    ],
  },
  // --- Original Data (TXN-20250305) ---
  {
    id: "TXN-20250305",
    vendorName: "GreenTech Solutions",
    vendorId: "VND-582904",
    businessType: "Electronics Supply",
    withdrawalRequestDate: "March 27, 2025",
    withdrawalAmount: "₦1,500,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "GTBank",
    accountNumber: "1234567890",
    receivingCountry: "Nigeria",
    ipAddress: "196.210.55.124",
    deviceBrowser: "Windows 11 - Edge 112.0",
    paymentStatus: "Pending",
    fraudRiskScore: 45,
    riskLevel: "Medium Risk",
    flaggedBy: "Manual Review",
    flagReason: "Large Withdrawal Amount",
    adminAssigned: "Jane Smith",
    status: "Pending Review",
    transactionHistory: [
      { id: 'TXN-20250304', date: '26/03/2025', amount: '3,200,000', method: 'Bank Transfer', location: 'Lagos, Nigeria 🇳🇬', status: 'Flagged' },
      { id: 'TXN-20250303', date: '03/03/2025', amount: '150,000', method: 'Mastercard', location: 'Lagos, Nigeria 🇳🇬', status: 'Completed' },
      { id: 'TXN-20250302', date: '02/03/2025', amount: '85,000', method: 'Visa Card', location: 'Lagos, Nigeria 🇳🇬', status: 'Completed' },
    ],
    relatedActivities: [
      { date: '20/03/2025', activity: 'New device logged in', status: 'Completed' },
      { date: '25/03/2025', activity: 'High value transaction initiated and canceled', status: 'Completed' },
    ],
  },
  // --- GENERATED PLACEHOLDER DATA (TXN-20250306 to TXN-20250314, and TXN-20250229, TXN-20250226 to TXN-20250223) ---
  {
    id: "TXN-20250314",
    vendorName: "Eko Logistics PLC",
    vendorId: "VND-109321",
    businessType: "Shipping and Delivery",
    withdrawalRequestDate: "April 05, 2025",
    withdrawalAmount: "₦250,000",
    withdrawalMethod: "Inter-Bank",
    bankName: "Zenith Bank",
    accountNumber: "9102938475",
    receivingCountry: "Nigeria",
    ipAddress: "105.112.89.21",
    deviceBrowser: "macOS - Safari 17.0",
    paymentStatus: "Successful",
    fraudRiskScore: 12,
    riskLevel: "Low Risk",
    flaggedBy: "None",
    flagReason: "N/A",
    adminAssigned: "Sarah Connor",
    status: "Completed",
    transactionHistory: [],
    relatedActivities: [{ date: '04/04/2025', activity: 'Standard weekly payout request', status: 'Completed' }],
  },
  {
    id: "TXN-20250313",
    vendorName: "Delta Software Hub",
    vendorId: "VND-400192",
    businessType: "IT Consulting",
    withdrawalRequestDate: "April 04, 2025",
    withdrawalAmount: "₦850,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "First Bank",
    accountNumber: "2837465910",
    receivingCountry: "Nigeria",
    ipAddress: "41.203.111.45",
    deviceBrowser: "Windows 10 - Chrome 123.0",
    paymentStatus: "Successful",
    fraudRiskScore: 31,
    riskLevel: "Low Risk",
    flaggedBy: "None",
    flagReason: "N/A",
    adminAssigned: "Sarah Connor",
    status: "Completed",
    transactionHistory: [],
    relatedActivities: [{ date: '03/04/2025', activity: 'Verified new bank account', status: 'Completed' }],
  },
  {
    id: "TXN-20250312",
    vendorName: "AquaPure Water",
    vendorId: "VND-678912",
    businessType: "Water Supply",
    withdrawalRequestDate: "April 03, 2025",
    withdrawalAmount: "₦1,100,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "Fidelity Bank",
    accountNumber: "5558883331",
    receivingCountry: "Nigeria",
    ipAddress: "102.89.76.54",
    deviceBrowser: "Android - Chrome 122.0",
    paymentStatus: "Successful",
    fraudRiskScore: 18,
    riskLevel: "Low Risk",
    flaggedBy: "None",
    flagReason: "N/A",
    adminAssigned: "Jane Smith",
    status: "Completed",
    transactionHistory: [],
    relatedActivities: [{ date: '02/04/2025', activity: 'Monthly recurring withdrawal processed', status: 'Completed' }],
  },
  {
    id: "TXN-20250311",
    vendorName: "Mega Hardware Stores",
    vendorId: "VND-123456",
    businessType: "Construction Supply",
    withdrawalRequestDate: "April 02, 2025",
    withdrawalAmount: "₦7,500,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "UBA",
    accountNumber: "1122334455",
    receivingCountry: "Nigeria",
    ipAddress: "197.210.12.34",
    deviceBrowser: "Windows 11 - Firefox 105.0",
    paymentStatus: "Pending",
    fraudRiskScore: 65,
    riskLevel: "High Risk",
    flaggedBy: "Automated Fraud Detection System",
    flagReason: "Exceeded daily velocity limit",
    adminAssigned: "John Doe (Fraud Analyst)",
    status: "Under Review",
    transactionHistory: [],
    relatedActivities: [{ date: '01/04/2025', activity: 'High volume of small sales transactions preceding withdrawal', status: 'Completed' }],
  },
  {
    id: "TXN-20250310",
    vendorName: "Fast Foods Inc.",
    vendorId: "VND-987654",
    businessType: "Restaurant",
    withdrawalRequestDate: "April 01, 2025",
    withdrawalAmount: "₦350,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "GTBank",
    accountNumber: "9988776655",
    receivingCountry: "Nigeria",
    ipAddress: "154.66.77.88",
    deviceBrowser: "iPhone - Chrome 121.0",
    paymentStatus: "Successful",
    fraudRiskScore: 5,
    riskLevel: "Low Risk",
    flaggedBy: "None",
    flagReason: "N/A",
    adminAssigned: "Jane Smith",
    status: "Completed",
    transactionHistory: [],
    relatedActivities: [{ date: '31/03/2025', activity: 'Routine daily reconciliation', status: 'Completed' }],
  },
  {
    id: "TXN-20250309",
    vendorName: "Prime Retail Services",
    vendorId: "VND-345678",
    businessType: "Supermarket Chain",
    withdrawalRequestDate: "March 31, 2025",
    withdrawalAmount: "₦2,100,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "Access Bank",
    accountNumber: "3322114455",
    receivingCountry: "Nigeria",
    ipAddress: "197.210.88.99",
    deviceBrowser: "Windows 10 - Edge 115.0",
    paymentStatus: "Successful",
    fraudRiskScore: 22,
    riskLevel: "Low Risk",
    flaggedBy: "None",
    flagReason: "N/A",
    adminAssigned: "Sarah Connor",
    status: "Completed",
    transactionHistory: [],
    relatedActivities: [{ date: '30/03/2025', activity: 'Large volume of transactions validated', status: 'Completed' }],
  },
  {
    id: "TXN-20250308",
    vendorName: "MedPharm Supplies",
    vendorId: "VND-210987",
    businessType: "Medical Supply",
    withdrawalRequestDate: "March 30, 2025",
    withdrawalAmount: "₦4,800,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "Zenith Bank",
    accountNumber: "7654321098",
    receivingCountry: "Nigeria",
    ipAddress: "41.203.44.11",
    deviceBrowser: "macOS - Chrome 122.0",
    paymentStatus: "Successful",
    fraudRiskScore: 39,
    riskLevel: "Medium Risk",
    flaggedBy: "Manual Review",
    flagReason: "High value/sensitive business type",
    adminAssigned: "Jane Smith",
    status: "Completed",
    transactionHistory: [],
    relatedActivities: [{ date: '29/03/2025', activity: 'Account details re-verified', status: 'Completed' }],
  },
  {
    id: "TXN-20250307",
    vendorName: "Astro Telecoms",
    vendorId: "VND-765432",
    businessType: "Airtime/Data Services",
    withdrawalRequestDate: "March 29, 2025",
    withdrawalAmount: "₦650,000",
    withdrawalMethod: "Inter-Bank",
    bankName: "First Bank",
    accountNumber: "1928374650",
    receivingCountry: "Nigeria",
    ipAddress: "105.100.20.30",
    deviceBrowser: "Android - Edge 118.0",
    paymentStatus: "Successful",
    fraudRiskScore: 8,
    riskLevel: "Low Risk",
    flaggedBy: "None",
    flagReason: "N/A",
    adminAssigned: "Sarah Connor",
    status: "Completed",
    transactionHistory: [],
    relatedActivities: [{ date: '28/03/2025', activity: 'Daily micro-transaction volume review', status: 'Completed' }],
  },
  {
    id: "TXN-20250306",
    vendorName: "Creative Designs Agency",
    vendorId: "VND-901234",
    businessType: "Creative Services",
    withdrawalRequestDate: "March 28, 2025",
    withdrawalAmount: "₦450,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "Fidelity Bank",
    accountNumber: "4567890123",
    receivingCountry: "Nigeria",
    ipAddress: "196.210.66.77",
    deviceBrowser: "Windows 10 - Chrome 121.0",
    paymentStatus: "Successful",
    fraudRiskScore: 15,
    riskLevel: "Low Risk",
    flaggedBy: "None",
    flagReason: "N/A",
    adminAssigned: "Jane Smith",
    status: "Completed",
    transactionHistory: [],
    relatedActivities: [{ date: '27/03/2025', activity: 'Routine weekly withdrawal', status: 'Completed' }],
  },
  {
    id: "TXN-20250229",
    vendorName: "Elite Educational Services",
    vendorId: "VND-554433",
    businessType: "Education",
    withdrawalRequestDate: "February 29, 2025",
    withdrawalAmount: "₦1,800,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "Access Bank",
    accountNumber: "9012345678",
    receivingCountry: "Nigeria",
    ipAddress: "41.203.22.33",
    deviceBrowser: "macOS - Safari 16.0",
    paymentStatus: "Successful",
    fraudRiskScore: 28,
    riskLevel: "Low Risk",
    flaggedBy: "None",
    flagReason: "N/A",
    adminAssigned: "Sarah Connor",
    status: "Completed",
    transactionHistory: [],
    relatedActivities: [{ date: '28/02/2025', activity: 'End of month financial reconciliation', status: 'Completed' }],
  },
  {
    id: "TXN-20250226",
    vendorName: "SecureNet Systems",
    vendorId: "VND-887766",
    businessType: "Cyber Security",
    withdrawalRequestDate: "February 26, 2025",
    withdrawalAmount: "₦4,000,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "Zenith Bank",
    accountNumber: "1230987456",
    receivingCountry: "Nigeria",
    ipAddress: "154.80.90.10",
    deviceBrowser: "Windows 11 - Chrome 120.0",
    paymentStatus: "Successful",
    fraudRiskScore: 55,
    riskLevel: "Medium Risk",
    flaggedBy: "Automated Fraud Detection System",
    flagReason: "High amount for vendor history",
    adminAssigned: "John Doe (Fraud Analyst)",
    status: "Completed",
    transactionHistory: [],
    relatedActivities: [{ date: '25/02/2025', activity: 'Manual verification of withdrawal amount', status: 'Completed' }],
  },
  {
    id: "TXN-20250225",
    vendorName: "Global Auto Parts",
    vendorId: "VND-334455",
    businessType: "Automotive Supply",
    withdrawalRequestDate: "February 25, 2025",
    withdrawalAmount: "₦950,000",
    withdrawalMethod: "Inter-Bank",
    bankName: "GTBank",
    accountNumber: "5678901234",
    receivingCountry: "Nigeria",
    ipAddress: "197.210.33.44",
    deviceBrowser: "Android - Firefox 100.0",
    paymentStatus: "Successful",
    fraudRiskScore: 10,
    riskLevel: "Low Risk",
    flaggedBy: "None",
    flagReason: "N/A",
    adminAssigned: "Jane Smith",
    status: "Completed",
    transactionHistory: [],
    relatedActivities: [{ date: '24/02/2025', activity: 'Routine weekly payout', status: 'Completed' }],
  },
  {
    id: "TXN-20250224",
    vendorName: "Digital Marketing Pro",
    vendorId: "VND-778899",
    businessType: "Marketing Agency",
    withdrawalRequestDate: "February 24, 2025",
    withdrawalAmount: "₦600,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "First Bank",
    accountNumber: "2345678901",
    receivingCountry: "Nigeria",
    ipAddress: "41.203.77.88",
    deviceBrowser: "macOS - Chrome 121.0",
    paymentStatus: "Successful",
    fraudRiskScore: 17,
    riskLevel: "Low Risk",
    flaggedBy: "None",
    flagReason: "N/A",
    adminAssigned: "Sarah Connor",
    status: "Completed",
    transactionHistory: [],
    relatedActivities: [{ date: '23/02/2025', activity: 'No unusual activity', status: 'Completed' }],
  },
  {
    id: "TXN-20250223",
    vendorName: "The Local Market",
    vendorId: "VND-112233",
    businessType: "General Retail",
    withdrawalRequestDate: "February 23, 2025",
    withdrawalAmount: "₦180,000",
    withdrawalMethod: "Bank Transfer",
    bankName: "Fidelity Bank",
    accountNumber: "8765432109",
    receivingCountry: "Nigeria",
    ipAddress: "105.112.99.00",
    deviceBrowser: "Android - Chrome 119.0",
    paymentStatus: "Successful",
    fraudRiskScore: 3,
    riskLevel: "Low Risk",
    flaggedBy: "None",
    flagReason: "N/A",
    adminAssigned: "Jane Smith",
    status: "Completed",
    transactionHistory: [],
    relatedActivities: [{ date: '22/02/2025', activity: 'Routine small withdrawal processed', status: 'Completed' }],
  },
];