// ../../MockData/PayoutData.js

export const mockPayouts = [
  // --- PAYOUT 1001 ---
  {
    id: "PAY-1001",
    status: "Pending",
    vendorName: "Vendor A",
    serviceType: "Gas Delivery",
    totalAmount: "₦50,000",
    paymentDate: "2025-03-16",
    paymentMethod: "Bank Transfer",
    processingAdmin: "N/A",
    referenceId: "REF-982325",
    vendor: {
      name: "Vendor A",
      businessName: "Vendor A Gas Services",
      contactEmail: "vendorA@email.com",
      phoneNumber: "+234-801-234-5678",
      bankName: "Zenith Bank",
      bankAccountNumber: "1234567890",
    },
  },
  // --- PAYOUT 1002 ---
  {
    id: "PAY-1002",
    status: "Approved",
    vendorName: "Logistics B",
    serviceType: "Logistics Fee",
    totalAmount: "₦65,000",
    paymentDate: "2025-03-17",
    paymentMethod: "Bank Transfer",
    processingAdmin: "Admin John",
    referenceId: "REF-345678",
    vendor: {
      name: "Logistics B",
      businessName: "B Transport Solutions",
      contactEmail: "logisticsb@email.com",
      phoneNumber: "+234-802-345-6789",
      bankName: "Access Bank",
      bankAccountNumber: "2345678901",
    },
  },
  // --- PAYOUT 1003 ---
  {
    id: "PAY-1003",
    status: "Pending",
    vendorName: "Delivery C",
    serviceType: "Delivery Fee",
    totalAmount: "₦35,500",
    paymentDate: "2025-03-18",
    paymentMethod: "Card Transfer",
    processingAdmin: "N/A",
    referenceId: "REF-678901",
    vendor: {
      name: "Delivery C",
      businessName: "C Courier Services",
      contactEmail: "deliveryc@email.com",
      phoneNumber: "+234-803-456-7890",
      bankName: "First Bank",
      bankAccountNumber: "3456789012",
    },
  },
  // --- PAYOUT 1004 ---
  {
    id: "PAY-1004",
    status: "Rejected",
    vendorName: "Vendor D",
    serviceType: "Maintenance",
    totalAmount: "₦92,000",
    paymentDate: "2025-03-19",
    paymentMethod: "Bank Transfer",
    processingAdmin: "Admin Jane",
    referenceId: "REF-901234",
    vendor: {
      name: "Vendor D",
      businessName: "D Technical Services",
      contactEmail: "vendord@email.com",
      phoneNumber: "+234-804-567-8901",
      bankName: "Zenith Bank",
      bankAccountNumber: "4567890123",
    },
  },
  // --- PAYOUT 1005 ---
  {
    id: "PAY-1005",
    status: "Pending",
    vendorName: "Vendor A",
    serviceType: "Gas Delivery",
    totalAmount: "₦50,000",
    paymentDate: "2025-03-20",
    paymentMethod: "Bank Transfer",
    processingAdmin: "N/A",
    referenceId: "REF-234567",
    vendor: {
      name: "Vendor A",
      businessName: "Vendor A Gas Services",
      contactEmail: "vendorA@email.com",
      phoneNumber: "+234-801-234-5678",
      bankName: "Zenith Bank",
      bankAccountNumber: "1234567890",
    },
  },
  // --- PAYOUT 1006 ---
  {
    id: "PAY-1006",
    status: "Approved",
    vendorName: "Logistics B",
    serviceType: "Logistics Fee",
    totalAmount: "₦110,000",
    paymentDate: "2025-03-21",
    paymentMethod: "Card Transfer",
    processingAdmin: "Admin John",
    referenceId: "REF-567890",
    vendor: {
      name: "Logistics B",
      businessName: "B Transport Solutions",
      contactEmail: "logisticsb@email.com",
      phoneNumber: "+234-802-345-6789",
      bankName: "Access Bank",
      bankAccountNumber: "2345678901",
    },
  },
  // --- PAYOUT 1007 ---
  {
    id: "PAY-1007",
    status: "Pending",
    vendorName: "Delivery C",
    serviceType: "Delivery Fee",
    totalAmount: "₦40,000",
    paymentDate: "2025-03-22",
    paymentMethod: "Bank Transfer",
    processingAdmin: "N/A",
    referenceId: "REF-890123",
    vendor: {
      name: "Delivery C",
      businessName: "C Courier Services",
      contactEmail: "deliveryc@email.com",
      phoneNumber: "+234-803-456-7890",
      bankName: "First Bank",
      bankAccountNumber: "3456789012",
    },
  },
  // --- PAYOUT 1008 ---
  {
    id: "PAY-1008",
    status: "Pending",
    vendorName: "Vendor D",
    serviceType: "Maintenance",
    totalAmount: "₦78,200",
    paymentDate: "2025-03-23",
    paymentMethod: "Bank Transfer",
    processingAdmin: "N/A",
    referenceId: "REF-123456",
    vendor: {
      name: "Vendor D",
      businessName: "D Technical Services",
      contactEmail: "vendord@email.com",
      phoneNumber: "+234-804-567-8901",
      bankName: "Zenith Bank",
      bankAccountNumber: "4567890123",
    },
  },
  // --- PAYOUT 1009 ---
  {
    id: "PAY-1009",
    status: "Approved",
    vendorName: "Vendor A",
    serviceType: "Gas Delivery",
    totalAmount: "₦58,000",
    paymentDate: "2025-03-24",
    paymentMethod: "Card Transfer",
    processingAdmin: "Admin Jane",
    referenceId: "REF-456789",
    vendor: {
      name: "Vendor A",
      businessName: "Vendor A Gas Services",
      contactEmail: "vendorA@email.com",
      phoneNumber: "+234-801-234-5678",
      bankName: "Zenith Bank",
      bankAccountNumber: "1234567890",
    },
  },
  // --- PAYOUT 1010 ---
  {
    id: "PAY-1010",
    status: "Pending",
    vendorName: "Logistics B",
    serviceType: "Logistics Fee",
    totalAmount: "₦155,000",
    paymentDate: "2025-03-25",
    paymentMethod: "Bank Transfer",
    processingAdmin: "N/A",
    referenceId: "REF-789012",
    vendor: {
      name: "Logistics B",
      businessName: "B Transport Solutions",
      contactEmail: "logisticsb@email.com",
      phoneNumber: "+234-802-345-6789",
      bankName: "Access Bank",
      bankAccountNumber: "2345678901",
    },
  },
  // --- PAYOUT 1011 ---
  {
    id: "PAY-1011",
    status: "Rejected",
    vendorName: "Delivery C",
    serviceType: "Delivery Fee",
    totalAmount: "₦31,000",
    paymentDate: "2025-03-26",
    paymentMethod: "Bank Transfer",
    processingAdmin: "Admin John",
    referenceId: "REF-012345",
    vendor: {
      name: "Delivery C",
      businessName: "C Courier Services",
      contactEmail: "deliveryc@email.com",
      phoneNumber: "+234-803-456-7890",
      bankName: "First Bank",
      bankAccountNumber: "3456789012",
    },
  },
  // --- PAYOUT 1012 ---
  {
    id: "PAY-1012",
    status: "Pending",
    vendorName: "Vendor D",
    serviceType: "Maintenance",
    totalAmount: "₦85,000",
    paymentDate: "2025-03-27",
    paymentMethod: "Bank Transfer",
    processingAdmin: "N/A",
    referenceId: "REF-345678",
    vendor: {
      name: "Vendor D",
      businessName: "D Technical Services",
      contactEmail: "vendord@email.com",
      phoneNumber: "+234-804-567-8901",
      bankName: "Zenith Bank",
      bankAccountNumber: "4567890123",
    },
  },
  // --- PAYOUT 1013 ---
  {
    id: "PAY-1013",
    status: "Approved",
    vendorName: "Vendor A",
    serviceType: "Gas Delivery",
    totalAmount: "₦51,500",
    paymentDate: "2025-03-28",
    paymentMethod: "Card Transfer",
    processingAdmin: "Admin Jane",
    referenceId: "REF-678901",
    vendor: {
      name: "Vendor A",
      businessName: "Vendor A Gas Services",
      contactEmail: "vendorA@email.com",
      phoneNumber: "+234-801-234-5678",
      bankName: "Zenith Bank",
      bankAccountNumber: "1234567890",
    },
  },
  // --- PAYOUT 1014 ---
  {
    id: "PAY-1014",
    status: "Pending",
    vendorName: "Logistics B",
    serviceType: "Logistics Fee",
    totalAmount: "₦99,000",
    paymentDate: "2025-03-29",
    paymentMethod: "Bank Transfer",
    processingAdmin: "N/A",
    referenceId: "REF-901234",
    vendor: {
      name: "Logistics B",
      businessName: "B Transport Solutions",
      contactEmail: "logisticsb@email.com",
      phoneNumber: "+234-802-345-6789",
      bankName: "Access Bank",
      bankAccountNumber: "2345678901",
    },
  },
  // --- PAYOUT 1015 ---
  {
    id: "PAY-1015",
    status: "Pending",
    vendorName: "Delivery C",
    serviceType: "Delivery Fee",
    totalAmount: "₦38,000",
    paymentDate: "2025-03-30",
    paymentMethod: "Bank Transfer",
    processingAdmin: "N/A",
    referenceId: "REF-234567",
    vendor: {
      name: "Delivery C",
      businessName: "C Courier Services",
      contactEmail: "deliveryc@email.com",
      phoneNumber: "+234-803-456-7890",
      bankName: "First Bank",
      bankAccountNumber: "3456789012",
    },
  },
  // --- PAYOUT 1016 ---
  {
    id: "PAY-1016",
    status: "Approved",
    vendorName: "Vendor D",
    serviceType: "Maintenance",
    totalAmount: "₦65,000",
    paymentDate: "2025-03-31",
    paymentMethod: "Card Transfer",
    processingAdmin: "Admin John",
    referenceId: "REF-567890",
    vendor: {
      name: "Vendor D",
      businessName: "D Technical Services",
      contactEmail: "vendord@email.com",
      phoneNumber: "+234-804-567-8901",
      bankName: "Zenith Bank",
      bankAccountNumber: "4567890123",
    },
  },
  // --- PAYOUT 1017 ---
  {
    id: "PAY-1017",
    status: "Rejected",
    vendorName: "Vendor A",
    serviceType: "Gas Delivery",
    totalAmount: "₦42,000",
    paymentDate: "2025-04-01",
    paymentMethod: "Bank Transfer",
    processingAdmin: "Admin Jane",
    referenceId: "REF-890123",
    vendor: {
      name: "Vendor A",
      businessName: "Vendor A Gas Services",
      contactEmail: "vendorA@email.com",
      phoneNumber: "+234-801-234-5678",
      bankName: "Zenith Bank",
      bankAccountNumber: "1234567890",
    },
  },
  // --- PAYOUT 1018 ---
  {
    id: "PAY-1018",
    status: "Pending",
    vendorName: "Logistics B",
    serviceType: "Logistics Fee",
    totalAmount: "₦140,000",
    paymentDate: "2025-04-02",
    paymentMethod: "Bank Transfer",
    processingAdmin: "N/A",
    referenceId: "REF-123456",
    vendor: {
      name: "Logistics B",
      businessName: "B Transport Solutions",
      contactEmail: "logisticsb@email.com",
      phoneNumber: "+234-802-345-6789",
      bankName: "Access Bank",
      bankAccountNumber: "2345678901",
    },
  },
  // --- PAYOUT 1019 ---
  {
    id: "PAY-1019",
    status: "Approved",
    vendorName: "Delivery C",
    serviceType: "Delivery Fee",
    totalAmount: "₦33,200",
    paymentDate: "2025-04-03",
    paymentMethod: "Card Transfer",
    processingAdmin: "Admin John",
    referenceId: "REF-456789",
    vendor: {
      name: "Delivery C",
      businessName: "C Courier Services",
      contactEmail: "deliveryc@email.com",
      phoneNumber: "+234-803-456-7890",
      bankName: "First Bank",
      bankAccountNumber: "3456789012",
    },
  },
  // --- PAYOUT 1020 ---
  {
    id: "PAY-1020",
    status: "Pending",
    vendorName: "Vendor D",
    serviceType: "Maintenance",
    totalAmount: "₦71,000",
    paymentDate: "2025-04-04",
    paymentMethod: "Bank Transfer",
    processingAdmin: "N/A",
    referenceId: "REF-789012",
    vendor: {
      name: "Vendor D",
      businessName: "D Technical Services",
      contactEmail: "vendord@email.com",
      phoneNumber: "+234-804-567-8901",
      bankName: "Zenith Bank",
      bankAccountNumber: "4567890123",
    },
  },
  // --- PAYOUT 1021 ---
  {
    id: "PAY-1021",
    status: "Rejected",
    vendorName: "Vendor A",
    serviceType: "Gas Delivery",
    totalAmount: "₦49,500",
    paymentDate: "2025-04-05",
    paymentMethod: "Bank Transfer",
    processingAdmin: "Admin Jane",
    referenceId: "REF-012345",
    vendor: {
      name: "Vendor A",
      businessName: "Vendor A Gas Services",
      contactEmail: "vendorA@email.com",
      phoneNumber: "+234-801-234-5678",
      bankName: "Zenith Bank",
      bankAccountNumber: "1234567890",
    },
  },
  // --- PAYOUT 1022 ---
  {
    id: "PAY-1022",
    status: "Pending",
    vendorName: "Logistics B",
    serviceType: "Logistics Fee",
    totalAmount: "₦105,000",
    paymentDate: "2025-04-06",
    paymentMethod: "Card Transfer",
    processingAdmin: "N/A",
    referenceId: "REF-345678",
    vendor: {
      name: "Logistics B",
      businessName: "B Transport Solutions",
      contactEmail: "logisticsb@email.com",
      phoneNumber: "+234-802-345-6789",
      bankName: "Access Bank",
      bankAccountNumber: "2345678901",
    },
  },
  // --- PAYOUT 1023 ---
  {
    id: "PAY-1023",
    status: "Approved",
    vendorName: "Delivery C",
    serviceType: "Delivery Fee",
    totalAmount: "₦30,000",
    paymentDate: "2025-04-07",
    paymentMethod: "Bank Transfer",
    processingAdmin: "Admin John",
    referenceId: "REF-678901",
    vendor: {
      name: "Delivery C",
      businessName: "C Courier Services",
      contactEmail: "deliveryc@email.com",
      phoneNumber: "+234-803-456-7890",
      bankName: "First Bank",
      bankAccountNumber: "3456789012",
    },
  },
  // --- PAYOUT 1024 (The last one) ---
  {
    id: "PAY-1024",
    status: "Pending",
    vendorName: "Vendor D",
    serviceType: "Maintenance",
    totalAmount: "₦70,000",
    paymentDate: "2025-04-08",
    paymentMethod: "Bank Transfer",
    processingAdmin: "N/A",
    referenceId: "REF-901234",
    vendor: {
      name: "Vendor D",
      businessName: "D Technical Services",
      contactEmail: "vendord@email.com",
      phoneNumber: "+234-804-567-8901",
      bankName: "Zenith Bank",
      bankAccountNumber: "4567890123",
    },
  },
];