export const MOCK_TRANSACTIONS = [
  {
    txnId: "TXN20250215",
    currentStep: 3,
    details: {
      "Transaction ID": "TXN20250215",
      "Transfer Date": "15/02/2025",
      "Processing Date": "16/02/2025 (if delayed, show reason)",
      "Amount Transferred": "₦1,000,000",
      Currency: "NGN (₦)",
      "Payment Gateway": "Flutterwave",
      "Payment Mode": "Bank Transfer",
      "Recipient Bank": "GTBank",
      "Account Name": "Quicrefill Company Ltd",
      "Account Number": "1234567890",
      "Transaction Status": "Completed",
      "Processing Duration": "24 hours (Auto-calculated)",
      "Admin in Charge": "John Doe (Who requested it?)",
      "Approval Date": "15/02/2025",
      "Reason for Transfer": "Profit Disbursement",
    },
    adminNotes: "Transfer Processed successfully without delay",
    logs: [
      {
        date: "15/02/2025 10:00 AM",
        action: "Transfer Requested",
        user: "Admin (John Doe)",
        details: "Requested ₦1M transfer",
      },
      {
        date: "15/02/2025 12:00 PM",
        action: "Transfer Approved",
        user: "Admin (Finance Team)",
        details: "Approved request",
      },
      {
        date: "15/02/2025 3:00 PM",
        action: "Transfer Processed",
        user: "Payment Gateway",
        details: "Successful transfer",
      },
      {
        date: "15/02/2025 3:30 PM",
        action: "Confirmation Sent",
        user: "System",
        details: "Auto-email sent to Admin",
      },
    ],
  },
// ---------------------------------------------------------------- //
  {
    txnId: "TXN20250216",
    currentStep: 3,
    details: {
      "Transaction ID": "TXN20250216",
      "Transfer Date": "16/02/2025",
      "Processing Date": "16/02/2025",
      "Amount Transferred": "₦500,000",
      Currency: "NGN (₦)",
      "Payment Gateway": "Paystack",
      "Payment Mode": "Bank Transfer",
      "Recipient Bank": "Zenith Bank",
      "Account Name": "Vendor Services Ltd",
      "Account Number": "0987654321",
      "Transaction Status": "Completed",
      "Processing Duration": "Instant (Auto-calculated)",
      "Admin in Charge": "Jane Smith",
      "Approval Date": "16/02/2025",
      "Reason for Transfer": "Vendor Payment",
    },
    adminNotes: "Instant transfer processed.",
    logs: [
      { date: "16/02/2025 09:00 AM", action: "Transfer Requested", user: "Admin (Jane Smith)", details: "Requested ₦500K transfer" },
      { date: "16/02/2025 09:05 AM", action: "Transfer Approved", user: "Admin (Finance Team)", details: "Approved request" },
      { date: "16/02/2025 09:06 AM", action: "Transfer Processed", user: "Payment Gateway", details: "Successful transfer" },
    ],
  },
// ---------------------------------------------------------------- //
  {
    txnId: "TXN20250217",
    currentStep: 2,
    details: {
      "Transaction ID": "TXN20250217",
      "Transfer Date": "17/02/2025",
      "Processing Date": "17/02/2025 (Pending approval)",
      "Amount Transferred": "₦250,000",
      Currency: "NGN (₦)",
      "Payment Gateway": "Flutterwave",
      "Payment Mode": "Wallet Transfer",
      "Recipient Bank": "N/A",
      "Account Name": "Customer Refund",
      "Account Number": "Customer ID: CUST9001",
      "Transaction Status": "Pending Approval",
      "Processing Duration": "N/A (Pending)",
      "Admin in Charge": "John Doe",
      "Approval Date": "N/A",
      "Reason for Transfer": "Customer Refund",
    },
    adminNotes: "Waiting for second-level finance approval.",
    logs: [
      { date: "17/02/2025 11:00 AM", action: "Transfer Requested", user: "Admin (John Doe)", details: "Requested ₦250K refund" },
      { date: "17/02/2025 11:30 AM", action: "Transfer Approved", user: "Admin (Team Lead)", details: "Initial approval given" },
    ],
  },
// ---------------------------------------------------------------- //
  {
    txnId: "TXN20250218",
    currentStep: 3,
    details: {
      "Transaction ID": "TXN20250218",
      "Transfer Date": "18/02/2025",
      "Processing Date": "18/02/2025",
      "Amount Transferred": "₦5,000,000",
      Currency: "NGN (₦)",
      "Payment Gateway": "Paystack",
      "Payment Mode": "Bank Transfer",
      "Recipient Bank": "Access Bank",
      "Account Name": "Capital Investment Trust",
      "Account Number": "1002003004",
      "Transaction Status": "Completed",
      "Processing Duration": "1 hour (Auto-calculated)",
      "Admin in Charge": "Jane Smith",
      "Approval Date": "18/02/2025",
      "Reason for Transfer": "Capital Injection",
    },
    adminNotes: "Large transfer successfully processed.",
    logs: [
      { date: "18/02/2025 02:00 PM", action: "Transfer Requested", user: "Admin (Jane Smith)", details: "Requested ₦5M transfer" },
      { date: "18/02/2025 02:45 PM", action: "Transfer Approved", user: "Director", details: "Approved request" },
      { date: "18/02/2025 03:00 PM", action: "Transfer Processed", user: "Payment Gateway", details: "Successful transfer" },
    ],
  },
// ---------------------------------------------------------------- //
  {
    txnId: "TXN20250219",
    currentStep: 1,
    details: {
      "Transaction ID": "TXN20250219",
      "Transfer Date": "19/02/2025",
      "Processing Date": "N/A (Cancelled)",
      "Amount Transferred": "₦150,000",
      Currency: "NGN (₦)",
      "Payment Gateway": "N/A",
      "Payment Mode": "Bank Transfer",
      "Recipient Bank": "Fidelity Bank",
      "Account Name": "Utility Payment",
      "Account Number": "5566778899",
      "Transaction Status": "Cancelled",
      "Processing Duration": "N/A",
      "Admin in Charge": "John Doe",
      "Approval Date": "N/A",
      "Reason for Transfer": "Utility Bill",
    },
    adminNotes: "Cancelled by Admin due to incorrect account number.",
    logs: [
      { date: "19/02/2025 09:30 AM", action: "Transfer Requested", user: "Admin (John Doe)", details: "Requested ₦150K transfer" },
      { date: "19/02/2025 09:45 AM", action: "Transfer Cancelled", user: "Admin (John Doe)", details: "Cancelled before approval" },
    ],
  },
// ---------------------------------------------------------------- //
  {
    txnId: "TXN20250220",
    currentStep: 3,
    details: {
      "Transaction ID": "TXN20250220",
      "Transfer Date": "20/02/2025",
      "Processing Date": "20/02/2025",
      "Amount Transferred": "₦300,000",
      Currency: "NGN (₦)",
      "Payment Gateway": "Flutterwave",
      "Payment Mode": "Bank Transfer",
      "Recipient Bank": "UBA",
      "Account Name": "Marketing Fund",
      "Account Number": "9001002003",
      "Transaction Status": "Completed",
      "Processing Duration": "30 minutes (Auto-calculated)",
      "Admin in Charge": "Jane Smith",
      "Approval Date": "20/02/2025",
      "Reason for Transfer": "Marketing Campaign Budget",
    },
    adminNotes: "Processed as routine transfer.",
    logs: [
      { date: "20/02/2025 1:00 PM", action: "Transfer Requested", user: "Admin (Jane Smith)", details: "Requested ₦300K transfer" },
      { date: "20/02/2025 1:15 PM", action: "Transfer Approved", user: "Admin (Finance Team)", details: "Approved request" },
      { date: "20/02/2025 1:30 PM", action: "Transfer Processed", user: "Payment Gateway", details: "Successful transfer" },
    ],
  },
// ---------------------------------------------------------------- //
  {
    txnId: "TXN20250221",
    currentStep: 3,
    details: {
      "Transaction ID": "TXN20250221",
      "Transfer Date": "21/02/2025",
      "Processing Date": "22/02/2025 (Delayed: Network Error)",
      "Amount Transferred": "₦80,000",
      Currency: "NGN (₦)",
      "Payment Gateway": "Paystack",
      "Payment Mode": "Bank Transfer",
      "Recipient Bank": "First Bank",
      "Account Name": "Petty Cash Reimbursement",
      "Account Number": "1122334455",
      "Transaction Status": "Failed",
      "Processing Duration": "N/A (Failed)",
      "Admin in Charge": "John Doe",
      "Approval Date": "21/02/2025",
      "Reason for Transfer": "Reimbursement",
    },
    adminNotes: "Transfer failed initially due to network issue, required manual re-initiation which was also unsuccessful.",
    logs: [
      { date: "21/02/2025 10:00 AM", action: "Transfer Requested", user: "Admin (John Doe)", details: "Requested ₦80K transfer" },
      { date: "21/02/2025 10:10 AM", action: "Transfer Approved", user: "Admin (Finance Team)", details: "Approved request" },
      { date: "21/02/2025 10:15 AM", action: "Transfer Failed", user: "Payment Gateway", details: "Network Timeout Error" },
      { date: "22/02/2025 09:00 AM", action: "Manual Retry", user: "Admin (Support)", details: "Transfer manually retried, still failed." },
    ],
  },
// ---------------------------------------------------------------- //
  {
    txnId: "TXN20250222",
    currentStep: 3,
    details: {
      "Transaction ID": "TXN20250222",
      "Transfer Date": "22/02/2025",
      "Processing Date": "22/02/2025",
      "Amount Transferred": "₦750,000",
      Currency: "NGN (₦)",
      "Payment Gateway": "Flutterwave",
      "Payment Mode": "Bank Transfer",
      "Recipient Bank": "Stanbic IBTC",
      "Account Name": "Operations Expense",
      "Account Number": "4455667788",
      "Transaction Status": "Completed",
      "Processing Duration": "Instant (Auto-calculated)",
      "Admin in Charge": "Jane Smith",
      "Approval Date": "22/02/2025",
      "Reason for Transfer": "Operational Expense",
    },
    adminNotes: "Successfully processed.",
    logs: [
      { date: "22/02/2025 11:30 AM", action: "Transfer Requested", user: "Admin (Jane Smith)", details: "Requested ₦750K transfer" },
      { date: "22/02/2025 11:35 AM", action: "Transfer Approved", user: "Admin (Finance Team)", details: "Approved request" },
      { date: "22/02/2025 11:36 AM", action: "Transfer Processed", user: "Payment Gateway", details: "Successful transfer" },
    ],
  },
// ---------------------------------------------------------------- //
  {
    txnId: "TXN20250223",
    currentStep: 3,
    details: {
      "Transaction ID": "TXN20250223",
      "Transfer Date": "23/02/2025",
      "Processing Date": "23/02/2025",
      "Amount Transferred": "₦20,000",
      Currency: "NGN (₦)",
      "Payment Gateway": "Paystack",
      "Payment Mode": "Card Payout",
      "Recipient Bank": "N/A",
      "Account Name": "Internal Testing",
      "Account Number": "CARD1234",
      "Transaction Status": "Completed",
      "Processing Duration": "Instant (Auto-calculated)",
      "Admin in Charge": "John Doe",
      "Approval Date": "23/02/2025",
      "Reason for Transfer": "System Test",
    },
    adminNotes: "Successful test transaction.",
    logs: [
      { date: "23/02/2025 01:00 PM", action: "Transfer Requested", user: "Admin (John Doe)", details: "Requested ₦20K test payout" },
      { date: "23/02/2025 01:01 PM", action: "Transfer Approved", user: "System", details: "Auto-approved" },
      { date: "23/02/2025 01:02 PM", action: "Transfer Processed", user: "Payment Gateway", details: "Successful transfer" },
    ],
  },
// ---------------------------------------------------------------- //
  {
    txnId: "TXN20250224",
    currentStep: 2,
    details: {
      "Transaction ID": "TXN20250224",
      "Transfer Date": "24/02/2025",
      "Processing Date": "N/A (Pending documentation)",
      "Amount Transferred": "₦1,500,000",
      Currency: "NGN (₦)",
      "Payment Gateway": "N/A",
      "Payment Mode": "Bank Transfer",
      "Recipient Bank": "GTBank",
      "Account Name": "Bulk Salary Payment",
      "Account Number": "9988776655",
      "Transaction Status": "On Hold",
      "Processing Duration": "N/A",
      "Admin in Charge": "Jane Smith",
      "Approval Date": "24/02/2025",
      "Reason for Transfer": "Salary Disbursement",
    },
    adminNotes: "On hold awaiting supporting payroll documentation.",
    logs: [
      { date: "24/02/2025 08:00 AM", action: "Transfer Requested", user: "Admin (Jane Smith)", details: "Requested ₦1.5M salary transfer" },
      { date: "24/02/2025 08:30 AM", action: "Transfer Approved", user: "HR Lead", details: "Approved payment list" },
      { date: "24/02/2025 09:00 AM", action: "Transfer Held", user: "Admin (Finance Team)", details: "Held: Missing documentation" },
    ],
  },
// ---------------------------------------------------------------- //
  {
    txnId: "TXN20250225",
    currentStep: 3,
    details: {
      "Transaction ID": "TXN20250225",
      "Transfer Date": "25/02/2025",
      "Processing Date": "25/02/2025",
      "Amount Transferred": "₦450,000",
      Currency: "NGN (₦)",
      "Payment Gateway": "Flutterwave",
      "Payment Mode": "Bank Transfer",
      "Recipient Bank": "Fidelity Bank",
      "Account Name": "Software Subscription",
      "Account Number": "1357924680",
      "Transaction Status": "Completed",
      "Processing Duration": "Instant (Auto-calculated)",
      "Admin in Charge": "John Doe",
      "Approval Date": "25/02/2025",
      "Reason for Transfer": "Monthly Subscription Fee",
    },
    adminNotes: "Processed successfully.",
    logs: [
      { date: "25/02/2025 03:00 PM", action: "Transfer Requested", user: "Admin (John Doe)", details: "Requested ₦450K subscription payment" },
      { date: "25/02/2025 03:05 PM", action: "Transfer Approved", user: "Admin (Team Lead)", details: "Approved request" },
      { date: "25/02/2025 03:06 PM", action: "Transfer Processed", user: "Payment Gateway", details: "Successful transfer" },
    ],
  },
// ---------------------------------------------------------------- //
  {
    txnId: "TXN20250226",
    currentStep: 3,
    details: {
      "Transaction ID": "TXN20250226",
      "Transfer Date": "26/02/2025",
      "Processing Date": "27/02/2025 (Delayed: High Volume)",
      "Amount Transferred": "₦600,000",
      Currency: "NGN (₦)",
      "Payment Gateway": "Paystack",
      "Payment Mode": "Bank Transfer",
      "Recipient Bank": "Zenith Bank",
      "Account Name": "Logistics Partner",
      "Account Number": "0011223344",
      "Transaction Status": "Completed",
      "Processing Duration": "24 hours (Auto-calculated)",
      "Admin in Charge": "Jane Smith",
      "Approval Date": "26/02/2025",
      "Reason for Transfer": "Logistics Fees",
    },
    adminNotes: "Delayed processing by payment gateway, completed next day.",
    logs: [
      { date: "26/02/2025 04:00 PM", action: "Transfer Requested", user: "Admin (Jane Smith)", details: "Requested ₦600K logistics payment" },
      { date: "26/02/2025 04:30 PM", action: "Transfer Approved", user: "Admin (Finance Team)", details: "Approved request" },
      { date: "27/02/2025 09:00 AM", action: "Transfer Processed", user: "Payment Gateway", details: "Successful transfer (Next Day)" },
    ],
  },
// ---------------------------------------------------------------- //
  {
    txnId: "TXN20250227",
    currentStep: 3,
    details: {
      "Transaction ID": "TXN20250227",
      "Transfer Date": "27/02/2025",
      "Processing Date": "27/02/2025",
      "Amount Transferred": "₦90,000",
      Currency: "NGN (₦)",
      "Payment Gateway": "Flutterwave",
      "Payment Mode": "Wallet Transfer",
      "Recipient Bank": "N/A",
      "Account Name": "Petty Cash Top-up",
      "Account Number": "WALLET-ID-A",
      "Transaction Status": "Completed",
      "Processing Duration": "Instant (Auto-calculated)",
      "Admin in Charge": "John Doe",
      "Approval Date": "27/02/2025",
      "Reason for Transfer": "Petty Cash",
    },
    adminNotes: "Wallet top-up successful.",
    logs: [
      { date: "27/02/2025 10:30 AM", action: "Transfer Requested", user: "Admin (John Doe)", details: "Requested ₦90K wallet top-up" },
      { date: "27/02/2025 10:35 AM", action: "Transfer Approved", user: "System", details: "Auto-approved" },
      { date: "27/02/2025 10:36 AM", action: "Transfer Processed", user: "Payment Gateway", details: "Successful transfer" },
    ],
  },
];