
export const VendorData=[
  {
    "vendorId": "VND-1001",
    "vendorName": "Supreme Gas Ltd",
    "ordersToday": 128,
    "avgDeliveryTime": "29 mins",
    "isFlagged": "No",
    "isSuspended": "No",
    "walletBalance": "1200000",
    "location": "Lagos"
  },
  {
    "vendorId": "VND-1002",
    "vendorName": "SafeFuel Energy",
    "ordersToday": 142,
    "avgDeliveryTime": "35 mins",
    "isFlagged": "Yes",
    "isSuspended": "No",
    "walletBalance": "500000",
    "location": "Abuja"
  },
  {
    "vendorId": "VND-1003",
    "vendorName": "Power Diesel",
    "ordersToday": 98,
    "avgDeliveryTime": "36 mins",
    "isFlagged": "No",
    "isSuspended": "No",
    "walletBalance": "700000",
    "location": "Lagos"
  },
  {
    "vendorId": "VND-1004",
    "vendorName": "Mega Refil",
    "ordersToday": 76,
    "avgDeliveryTime": "42 mins",
    "isFlagged": "Yes",
    "isSuspended": "No",
    "walletBalance": "300000",
    "location": "Abuja"
  },
  {
    "vendorId": "VND-1005",
    "vendorName": "Apex Oil",
    "ordersToday": 200,
    "avgDeliveryTime": "27 mins",
    "isFlagged": "No",
    "isSuspended": "No",
    "walletBalance": "2000000",
    "location": "Lagos"
  },
  {
    "vendorId": "VND-1006",
    "vendorName": "Express Gas",
    "ordersToday": 55,
    "avgDeliveryTime": "40 mins",
    "isFlagged": "No",
    "isSuspended": "Yes (Temp)",
    "walletBalance": "150000",
    "location": "Lagos"
  },
  {
    "vendorId": "VND-1007",
    "vendorName": "Petroleum Hub",
    "ordersToday": 110,
    "avgDeliveryTime": "30 mins",
    "isFlagged": "No",
    "isSuspended": "No",
    "walletBalance": "1000000",
    "location": "Port Harcourt"
  },
  {
    "vendorId": "VND-1008",
    "vendorName": "EcoFuel Nigeria",
    "ordersToday": 98,
    "avgDeliveryTime": "29 mins",
    "isFlagged": "Yes",
    "isSuspended": "No",
    "walletBalance": "350000",
    "location": "Lagos"
  },
  {
    "vendorId": "VND-1009",
    "vendorName": "Energy Plus",
    "ordersToday": 85,
    "avgDeliveryTime": "41 mins",
    "isFlagged": "No",
    "isSuspended": "No",
    "walletBalance": "250000",
    "location": "Abuja"
  },
  {
    "vendorId": "VND-1010",
    "vendorName": "Clean Fuel",
    "ordersToday": 65,
    "avgDeliveryTime": "33 mins",
    "isFlagged": "No",
    "isSuspended": "Yes (Perm)",
    "walletBalance": "120000",
    "location": "Abuja"
  },
  {
    "vendorId": "VND-1011",
    "vendorName": "Reliable Diesel",
    "ordersToday": 145,
    "avgDeliveryTime": "37 mins",
    "isFlagged": "No",
    "isSuspended": "No",
    "walletBalance": "1300000",
    "location": "Port Harcourt"
  },
  {
    "vendorId": "VND-1012",
    "vendorName": "Secure Gas Ltd",
    "ordersToday": 70,
    "avgDeliveryTime": "31 mins",
    "isFlagged": "Yes",
    "isSuspended": "No",
    "walletBalance": "450000",
    "location": "Port Harcourt"
  },
  {
    "vendorId": "VND-1013",
    "vendorName": "Urban Energy",
    "ordersToday": 90,
    "avgDeliveryTime": "35 mins",
    "isFlagged": "No",
    "isSuspended": "No",
    "walletBalance": "600000",
    "location": "Kano"
  },
  {
    "vendorId": "VND-1014",
    "vendorName": "FastTrack Oil",
    "ordersToday": 115,
    "avgDeliveryTime": "28 mins",
    "isFlagged": "No",
    "isSuspended": "No",
    "walletBalance": "900000",
    "location": "Kano"
  },
  {
    "vendorId": "VND-1015",
    "vendorName": "Supreme Petroleum",
    "ordersToday": 155,
    "avgDeliveryTime": "39 mins",
    "isFlagged": "No",
    "isSuspended": "No",
    "walletBalance": "1800000",
    "location": "Lagos"
  }
];

import { FaThumbtack, FaOilCan, FaFire, FaGasPump, FaClipboardCheck } from 'react-icons/fa';


  export const deliveryData = [
  {
    label: 'Total Pending Vendors',
    value: '125',
    bg: 'bg-amber-500',
    icon: <FaThumbtack className="text-black text-md" />,
  },
  {
    label: 'Vendor Awaiting Review',
    value: '20',
    bg: 'bg-amber-300',
    icon: <FaOilCan className="text-black text-md" />,
  },
  {
    label: 'Vendor Flagged for Compliance Issues',
    value: '45',
    bg: 'bg-teal-300',
    icon: <FaFire className="text-black text-md" />,
  },
  {
    label: 'Vendor Pending More Information',
    value: '25',
    bg: 'bg-green-500',
    icon: <FaClipboardCheck className="text-white text-md" />,
  },
];


export const PendingVendorData =[
  {
    "vendorId": "VND-001",
    "businessName": "Supreme Gas Ltd",
    "vendorName": "John Doe",
    "category": "Gas Refill",
    "region": "Lagos",
    "dateSubmitted": "2025-03-11",
    "complianceDocs": "✅ 4/6",
    "status": "Pending"
  },
  {
    "vendorId": "VND-002",
    "businessName": "Fast Diesel Co.",
    "vendorName": "Jane Smith",
    "category": "Diesel",
    "region": "Lagos",
    "dateSubmitted": "2025-03-09",
    "complianceDocs": "✅ 6/6",
    "status": "Pending"
  },
  {
    "vendorId": "VND-003",
    "businessName": "Mega Gas Nigeria",
    "vendorName": "Richard Obi",
    "category": "Gas Refill",
    "region": "Port Harcourt",
    "dateSubmitted": "2025-03-08",
    "complianceDocs": "❌ 3/6",
    "status": "More Info Needed"
  },
  {
    "vendorId": "VND-004",
    "businessName": "PetroSwift",
    "vendorName": "James Abdul",
    "category": "Petroleum",
    "region": "Abuja",
    "dateSubmitted": "2025-03-06",
    "complianceDocs": "❌ 5/6",
    "status": "Pending"
  },
  {
    "vendorId": "VND-005",
    "businessName": "Elite Energy",
    "vendorName": "Sarah Johnson",
    "category": "Accessories",
    "region": "Abuja",
    "dateSubmitted": "2025-03-04",
    "complianceDocs": "✅ 6/6",
    "status": "Pending"
  },
  {
    "vendorId": "VND-006",
    "businessName": "EcoGas Limited",
    "vendorName": "Emeka Okeke",
    "category": "Gas Refill",
    "region": "Lagos",
    "dateSubmitted": "2025-03-03",
    "complianceDocs": "❌ 2/6",
    "status": "Flagged"
  },
  {
    "vendorId": "VND-007",
    "businessName": "Energy Plus Ltd",
    "vendorName": "Ibrahim Bello",
    "category": "Diesel",
    "region": "Kano",
    "dateSubmitted": "2025-02-29",
    "complianceDocs": "✅ 6/6",
    "status": "Pending"
  },
  {
    "vendorId": "VND-008",
    "businessName": "SolarTech Nigeria",
    "vendorName": "Aisha Musa",
    "category": "Diesel",
    "region": "Kano",
    "dateSubmitted": "2025-02-26",
    "complianceDocs": "❌ 5/6",
    "status": "Pending"
  },
  {
    "vendorId": "VND-009",
    "businessName": "Superior Oil",
    "vendorName": "David Umeh",
    "category": "Petroleum",
    "region": "Abuja",
    "dateSubmitted": "2025-02-23",
    "complianceDocs": "❌ 4/6",
    "status": "More Info Needed"
  },
  {
    "vendorId": "VND-010",
    "businessName": "Bright Gas",
    "vendorName": "Michael Eze",
    "category": "Gas Refill",
    "region": "Port Harcourt",
    "dateSubmitted": "2025-02-20",
    "complianceDocs": "✅ 6/6",
    "status": "Pending"
  },
  {
    "vendorId": "VND-011",
    "businessName": "Zenith Fuels",
    "vendorName": "Funke Adeyemi",
    "category": "Diesel",
    "region": "Port Harcourt",
    "dateSubmitted": "2025-02-18",
    "complianceDocs": "✅ 6/6",
    "status": "Pending"
  },
  {
    "vendorId": "VND-012",
    "businessName": "Green Energy Ltd",
    "vendorName": "Paul Ekong",
    "category": "Petroleum",
    "region": "Lagos",
    "dateSubmitted": "2025-02-15",
    "complianceDocs": "❌ 3/6",
    "status": "More Info Needed"
  },
  {
    "vendorId": "VND-013",
    "businessName": "Nationwide Gas",
    "vendorName": "Ifeoma Chika",
    "category": "Petroleum",
    "region": "Lagos",
    "dateSubmitted": "2025-02-12",
    "complianceDocs": "✅ 6/6",
    "status": "Pending"
  },
  {
    "vendorId": "VND-014",
    "businessName": "Rapid Oil Ltd",
    "vendorName": "Usman Garba",
    "category": "Diesel",
    "region": "Abuja",
    "dateSubmitted": "2025-02-10",
    "complianceDocs": "✅ 6/6",
    "status": "Pending"
  },
  {
    "vendorId": "VND-015",
    "businessName": "Superior Diesel",
    "vendorName": "Tunde Olagunju",
    "category": "Gas Refill",
    "region": "Abuja",
    "dateSubmitted": "2025-02-07",
    "complianceDocs": "❌ 4/6",
    "status": "More Info Needed"
  },
  {
    "vendorId": "VND-016",
    "businessName": "KeroFlow Services",
    "vendorName": "Chinedu Ibe",
    "category": "Gas Refill",
    "region": "Lagos",
    "dateSubmitted": "2025-02-05",
    "complianceDocs": "❌ 5/6",
    "status": "Pending"
  }
]
export const vendorDetailsData = [
  {
    "vendorId": "VND-1001",
    "businessName": "Supreme Gas Ltd",
    "vendorName": "John Doe",
    "category": "Gas Refill",
    "region": "Lagos",
    "dateSubmitted": "2025-03-11",
    "complianceDocs": "✅ 4/6",
    "status": "Pending",
    "walletBalance": "₦0",
    "totalOrdersFulfilled": "0",
    "avgDeliveryTime": "N/A",
    "warnings": 0,
    "suspensions": "0 Suspensions",
    "registrationDate": "N/A",
    "contactInfo": "pending@supremegas.com | +234 800 123 001"
  },
  {
    "vendorId": "VND-1002",
    "businessName": "SafeFuel Energy",
    "vendorName": "Sarah Johnson",
    "category": "Diesel",
    "region": "Abuja",
    "dateSubmitted": "2023-02-14",
    "complianceDocs": "✅ 6/6",
    "status": "Active",
    "walletBalance": "₦500,000",
    "totalOrdersFulfilled": "12,435",
    "avgDeliveryTime": "35 mins",
    "warnings": 2,
    "suspensions": "1 Suspension (Temporary)",
    "registrationDate": "Feb 14, 2023",
    "contactInfo": "safefuel@gmail.com | +234 800 123 4657"
  },
  {
    "vendorId": "VND-1003",
    "businessName": "Mega Gas Nigeria",
    "vendorName": "Richard Obi",
    "category": "Gas Refill",
    "region": "Port Harcourt",
    "dateSubmitted": "2025-03-08",
    "complianceDocs": "❌ 3/6",
    "status": "More Info Needed",
    "walletBalance": "₦0",
    "totalOrdersFulfilled": "0",
    "avgDeliveryTime": "N/A",
    "warnings": 0,
    "suspensions": "0 Suspensions",
    "registrationDate": "N/A",
    "contactInfo": "pending@megagas.com | +234 800 123 003"
  },
  {
    "vendorId": "VND-1004",
    "businessName": "PetroSwift Logistics",
    "vendorName": "James Abdul",
    "category": "Petroleum",
    "region": "Abuja",
    "dateSubmitted": "2024-06-20",
    "complianceDocs": "✅ 6/6",
    "status": "Active",
    "walletBalance": "₦920,500",
    "totalOrdersFulfilled": "25,109",
    "avgDeliveryTime": "45 mins",
    "warnings": 0,
    "suspensions": "0 Suspensions",
    "registrationDate": "Jun 20, 2024",
    "contactInfo": "support@petroswift.com | +234 800 123 104"
  },
  {
    "vendorId": "VND-1005",
    "businessName": "Elite Energy Solutions",
    "vendorName": "David Umeh",
    "category": "Accessories",
    "region": "Abuja",
    "dateSubmitted": "2024-11-01",
    "complianceDocs": "✅ 6/6",
    "status": "Active",
    "walletBalance": "₦350,000",
    "totalOrdersFulfilled": "8,700",
    "avgDeliveryTime": "28 mins",
    "warnings": 0,
    "suspensions": "0 Suspensions",
    "registrationDate": "Nov 01, 2024",
    "contactInfo": "elite.energy@info.com | +234 901 222 3333"
  },
  {
    "vendorId": "VND-1006",
    "businessName": "EcoGas Limited",
    "vendorName": "Emeka Okeke",
    "category": "Gas Refill",
    "region": "Lagos",
    "dateSubmitted": "2025-03-03",
    "complianceDocs": "❌ 2/6",
    "status": "Flagged",
    "walletBalance": "₦0",
    "totalOrdersFulfilled": "0",
    "avgDeliveryTime": "N/A",
    "warnings": 0,
    "suspensions": "0 Suspensions",
    "registrationDate": "N/A",
    "contactInfo": "pending@ecogas.com | +234 800 123 006"
  },
  {
    "vendorId": "VND-1007",
    "businessName": "Energy Plus Ltd",
    "vendorName": "Ibrahim Bello",
    "category": "Diesel",
    "region": "Kano",
    "dateSubmitted": "2024-09-15",
    "complianceDocs": "✅ 6/6",
    "status": "Active",
    "walletBalance": "₦615,000",
    "totalOrdersFulfilled": "15,220",
    "avgDeliveryTime": "40 mins",
    "warnings": 1,
    "suspensions": "0 Suspensions",
    "registrationDate": "Sep 15, 2024",
    "contactInfo": "ibrahim@energyplus.net | +234 805 111 5555"
  },
  {
    "vendorId": "VND-1008",
    "businessName": "SolarTech Nigeria",
    "vendorName": "Aisha Musa",
    "category": "Diesel",
    "region": "Kano",
    "dateSubmitted": "2025-01-29",
    "complianceDocs": "❌ 5/6",
    "status": "Pending",
    "walletBalance": "₦0",
    "totalOrdersFulfilled": "0",
    "avgDeliveryTime": "N/A",
    "warnings": 0,
    "suspensions": "0 Suspensions",
    "registrationDate": "N/A",
    "contactInfo": "pending@solartech.com | +234 803 999 8888"
  },
  {
    "vendorId": "VND-1009",
    "businessName": "Superior Oil Co.",
    "vendorName": "Grace Adeyemi",
    "category": "Petroleum",
    "region": "Abuja",
    "dateSubmitted": "2023-10-05",
    "complianceDocs": "✅ 6/6",
    "status": "Active",
    "walletBalance": "₦1,200,000",
    "totalOrdersFulfilled": "35,670",
    "avgDeliveryTime": "50 mins",
    "warnings": 3,
    "suspensions": "1 Suspension (Permanent)",
    "registrationDate": "Oct 05, 2023",
    "contactInfo": "sales@superioroil.ng | +234 700 444 7777"
  },
  {
    "vendorId": "VND-1010",
    "businessName": "Bright Gas Refills",
    "vendorName": "Michael Eze",
    "category": "Gas Refill",
    "region": "Port Harcourt",
    "dateSubmitted": "2024-03-20",
    "complianceDocs": "✅ 6/6",
    "status": "Active",
    "walletBalance": "₦450,000",
    "totalOrdersFulfilled": "10,120",
    "avgDeliveryTime": "32 mins",
    "warnings": 0,
    "suspensions": "0 Suspensions",
    "registrationDate": "Mar 20, 2024",
    "contactInfo": "info@brightgas.com | +234 810 555 1212"
  },
  {
    "vendorId": "VND-1011",
    "businessName": "Zenith Fuels Inc.",
    "vendorName": "Funke Adeyemi",
    "category": "Diesel",
    "region": "Port Harcourt",
    "dateSubmitted": "2024-01-18",
    "complianceDocs": "✅ 6/6",
    "status": "Active",
    "walletBalance": "₦880,000",
    "totalOrdersFulfilled": "22,500",
    "avgDeliveryTime": "38 mins",
    "warnings": 0,
    "suspensions": "0 Suspensions",
    "registrationDate": "Jan 18, 2024",
    "contactInfo": "funke@zenithfuels.com | +234 905 666 8888"
  },
  {
    "vendorId": "VND-1012",
    "businessName": "Green Energy Ltd",
    "vendorName": "Paul Ekong",
    "category": "Petroleum",
    "region": "Lagos",
    "dateSubmitted": "2025-02-15",
    "complianceDocs": "❌ 3/6",
    "status": "More Info Needed",
    "walletBalance": "₦0",
    "totalOrdersFulfilled": "0",
    "avgDeliveryTime": "N/A",
    "warnings": 0,
    "suspensions": "0 Suspensions",
    "registrationDate": "N/A",
    "contactInfo": "pending@greenenergy.com | +234 807 123 4567"
  },
  {
    "vendorId": "VND-1013",
    "businessName": "Nationwide Gas Supply",
    "vendorName": "Ifeoma Chika",
    "category": "Gas Refill",
    "region": "Lagos",
    "dateSubmitted": "2023-08-01",
    "complianceDocs": "✅ 6/6",
    "status": "Active",
    "walletBalance": "₦710,000",
    "totalOrdersFulfilled": "18,900",
    "avgDeliveryTime": "30 mins",
    "warnings": 1,
    "suspensions": "0 Suspensions",
    "registrationDate": "Aug 01, 2023",
    "contactInfo": "ifeoma@nationwidegas.ng | +234 808 222 7777"
  },
  {
    "vendorId": "VND-1014",
    "businessName": "Rapid Oil Services",
    "vendorName": "Usman Garba",
    "category": "Diesel",
    "region": "Abuja",
    "dateSubmitted": "2024-05-10",
    "complianceDocs": "✅ 6/6",
    "status": "Active",
    "walletBalance": "₦950,000",
    "totalOrdersFulfilled": "28,400",
    "avgDeliveryTime": "42 mins",
    "warnings": 0,
    "suspensions": "0 Suspensions",
    "registrationDate": "May 10, 2024",
    "contactInfo": "usman@rapidoil.com | +234 903 555 9999"
  },
  {
    "vendorId": "VND-1015",
    "businessName": "Superior Diesel Power",
    "vendorName": "Tunde Olagunju",
    "category": "Diesel",
    "region": "Abuja",
    "dateSubmitted": "2025-02-07",
    "complianceDocs": "❌ 4/6",
    "status": "More Info Needed",
    "walletBalance": "₦0",
    "totalOrdersFulfilled": "0",
    "avgDeliveryTime": "N/A",
    "warnings": 0,
    "suspensions": "0 Suspensions",
    "registrationDate": "N/A",
    "contactInfo": "pending@superiordiesel.com | +234 812 000 1111"
  },
  {
    "vendorId": "VND-1016",
    "businessName": "KeroFlow Services",
    "vendorName": "Chinedu Ibe",
    "category": "Gas Refill",
    "region": "Lagos",
    "dateSubmitted": "2025-02-05",
    "complianceDocs": "❌ 5/6",
    "status": "Pending",
    "walletBalance": "₦0",
    "totalOrdersFulfilled": "0",
    "avgDeliveryTime": "N/A",
    "warnings": 0,
    "suspensions": "0 Suspensions",
    "registrationDate": "N/A",
    "contactInfo": "pending@keroflow.com | +234 806 777 6666"
  }
];
export const PENDING_VENDOR_MOCK_DATA_LIST = [
    // 1
    {
        vendorId: 'VND-001',
        businessName: 'Supreme Gas Ltd',
        vendorName: 'John Doe',
        phoneNumber: '+234 8012345678',
        emailAddress: 'johndoe@supremegas.com',
        businessAddress: '23 Energy Road, Lagos',
        category: 'Gas Refill',
        dateApplied: '2025-03-10',
        website: 'www.supremegas.com',
        socialMedia: '@supremegasng (Instagram)',
    },
    // 2
    {
        vendorId: 'VND-002',
        businessName: 'Fresh Farms Produce',
        vendorName: 'Aisha Bello',
        phoneNumber: '+234 9087654321',
        emailAddress: 'aisha@freshfarms.net',
        businessAddress: '15 Market Square, Abuja',
        category: 'Groceries',
        dateApplied: '2025-03-15',
        website: 'www.freshfarms.net',
        socialMedia: 'FreshFarmsNG (Facebook)',
    },
    // 3
    {
        vendorId: 'VND-003',
        businessName: 'Tech Fix Solutions',
        vendorName: 'Chidi Okoro',
        phoneNumber: '+234 7011223344',
        emailAddress: 'chidi@techfix.com',
        businessAddress: '4 Silicon Alley, Port Harcourt',
        category: 'Electronics',
        dateApplied: '2025-03-18',
        website: 'www.techfixsol.com',
        socialMedia: 'TechFixPH (Twitter)',
    },
    // 4
    {
        vendorId: 'VND-004',
        businessName: 'The Book Nook',
        vendorName: 'Bisi Adebayo',
        phoneNumber: '+234 8109876543',
        emailAddress: 'bisi@booknook.com',
        businessAddress: '10 University Road, Ibadan',
        category: 'Books',
        dateApplied: '2025-03-22',
        website: '',
        socialMedia: 'BookNookReads (Instagram)',
    },
    // 5
    {
        vendorId: 'VND-005',
        businessName: 'Global Logistics Express',
        vendorName: 'Tunde Musa',
        phoneNumber: '+234 9054321098',
        emailAddress: 'tunde@globalexpress.com',
        businessAddress: '30 Port Access Way, Apapa',
        category: 'Logistics',
        dateApplied: '2025-03-25',
        website: 'www.globalexpresslogistics.net',
        socialMedia: 'GlobalExpress (LinkedIn)',
    },
    // 6
    {
        vendorId: 'VND-006',
        businessName: 'Artisan Bakes & Treats',
        vendorName: 'Fatima Umar',
        phoneNumber: '+234 8023456789',
        emailAddress: 'fatima@artisanbakes.com',
        businessAddress: '8 Bakery Lane, Kano',
        category: 'Food & Beverage',
        dateApplied: '2025-04-01',
        website: 'www.artisanbakes.com',
        socialMedia: '@ArtisanBakesNG (Instagram)',
    },
    // 7
    {
        vendorId: 'VND-007',
        businessName: 'Clean Sweep Services',
        vendorName: 'Kunle Adeleke',
        phoneNumber: '+234 7056789012',
        emailAddress: 'kunle@cleansweep.com',
        businessAddress: '12 Maintenance Road, Kaduna',
        category: 'Home Services',
        dateApplied: '2025-04-05',
        website: '',
        socialMedia: 'CleanSweepKaduna (Facebook)',
    },
    // 8
    {
        vendorId: 'VND-008',
        businessName: 'Trendy Fashion Hub',
        vendorName: 'Ngozi Ezenwa',
        phoneNumber: '+234 8134567890',
        emailAddress: 'ngozi@trendyhub.com',
        businessAddress: '7 Style Street, Enugu',
        category: 'Apparel',
        dateApplied: '2025-04-09',
        website: 'www.trendyfashionhub.store',
        socialMedia: 'TrendyHubNG (TikTok)',
    },
    // 9
    {
        vendorId: 'VND-009',
        businessName: 'Auto Repair Pro',
        vendorName: 'Emeka Dike',
        phoneNumber: '+234 9021098765',
        emailAddress: 'emeka@autorepairpro.net',
        businessAddress: '2 Garage Road, Owerri',
        category: 'Automotive',
        dateApplied: '2025-04-14',
        website: '',
        socialMedia: 'AutoRepairProOwerri (Facebook)',
    },
    // 10
    {
        vendorId: 'VND-010',
        businessName: 'Pet Wellness Clinic',
        vendorName: 'Dr. Zaki Audu',
        phoneNumber: '+234 8078901234',
        emailAddress: 'zaki@petwellness.com',
        businessAddress: '5 Animal Avenue, Jos',
        category: 'Pet Supplies',
        dateApplied: '2025-04-18',
        website: 'www.petwellnessclinic.org',
        socialMedia: '@PetWellnessJos (Instagram)',
    },
    // 11
    {
        vendorId: 'VND-011',
        businessName: 'Eco-Friendly Crafts',
        vendorName: 'Hadiza Kabir',
        phoneNumber: '+234 7045678901',
        emailAddress: 'hadiza@ecocrafts.com',
        businessAddress: '1 Artisan Depot, Gombe',
        category: 'Handicrafts',
        dateApplied: '2025-04-25',
        website: 'www.ecofriendlycrafts.ng',
        socialMedia: 'EcoCraftsNG (Pinterest)',
    },
    // 12
    {
        vendorId: 'VND-012',
        businessName: 'SecureIT Solutions',
        vendorName: 'Femi Johnson',
        phoneNumber: '+234 8167890123',
        emailAddress: 'femi@secureitsolutions.net',
        businessAddress: '9 Cyber Street, Lagos',
        category: 'Software/IT',
        dateApplied: '2025-05-01',
        website: 'www.secureitsolutions.ng',
        socialMedia: 'SecureIT Lagos (LinkedIn)',
    },
    // 13
    {
        vendorId: 'VND-013',
        businessName: 'Healthy Meal Prep',
        vendorName: 'Grace Obaseki',
        phoneNumber: '+234 9032109876',
        emailAddress: 'grace@healthymealprep.com',
        businessAddress: '11 Fitness Road, Benin City',
        category: 'Food & Beverage',
        dateApplied: '2025-05-05',
        website: '',
        socialMedia: '@HealthyMealPrepNG (Instagram)',
    },
    // 14
    {
        vendorId: 'VND-014',
        businessName: 'Solar Power Installers',
        vendorName: 'Musa Abdullahi',
        phoneNumber: '+234 8098765432',
        emailAddress: 'musa@solarpower.com',
        businessAddress: '2 Power Grid Street, Sokoto',
        category: 'Home Improvement',
        dateApplied: '2025-05-12',
        website: 'www.solarpowerinstallers.ng',
        socialMedia: 'SolarPowerSokoto (Twitter)',
    },
    // 15
    {
        vendorId: 'VND-015',
        businessName: 'Kids Toy Paradise',
        vendorName: 'Blessing Kalu',
        phoneNumber: '+234 7065432109',
        emailAddress: 'blessing@toyparadise.com',
        businessAddress: '17 Play Zone, Calabar',
        category: 'Toys',
        dateApplied: '2025-05-19',
        website: 'www.kidstoyparadise.store',
        socialMedia: 'ToyParadise (Facebook)',
    },
    // 16
    {
        vendorId: 'VND-016',
        businessName: 'The Gourmet Spices',
        vendorName: 'Ahmed Shehu',
        phoneNumber: '+234 8121098765',
        emailAddress: 'ahmed@gourmetspices.com',
        businessAddress: '4 Spice Market, Zaria',
        category: 'Groceries',
        dateApplied: '2025-05-23',
        website: '',
        socialMedia: 'GourmetSpicesZaria (Instagram)',
    },
    // 17
    {
        vendorId: 'VND-017',
        businessName: 'Digital Marketing Agency',
        vendorName: 'Uche Nnamdi',
        phoneNumber: '+234 9012345678',
        emailAddress: 'uche@digitalmarketing.com',
        businessAddress: '6 Innovation Hub, Aba',
        category: 'Services',
        dateApplied: '2025-06-01',
        website: 'www.digitalmarketingagency.biz',
        socialMedia: 'DigitalMktAba (LinkedIn)',
    },
    // 18
    {
        vendorId: 'VND-018',
        businessName: 'Office Supplies King',
        vendorName: 'Amaka Eze',
        phoneNumber: '+234 8034567890',
        emailAddress: 'amaka@officesuppliesking.com',
        businessAddress: '14 Stationery Road, Onitsha',
        category: 'Office Supplies',
        dateApplied: '2025-06-06',
        website: 'www.officesuppliesking.com',
        socialMedia: '',
    },
    // 19
    {
        vendorId: 'VND-019',
        businessName: 'Local Honey Producers',
        vendorName: 'Danjuma Bako',
        phoneNumber: '+234 7078901234',
        emailAddress: 'danjuma@localhoney.net',
        businessAddress: '2 Bee Farm, Bauchi',
        category: 'Food & Beverage',
        dateApplied: '2025-06-10',
        website: '',
        socialMedia: 'LocalHoneyBauchi (Facebook)',
    },
    // 20
    {
        vendorId: 'VND-020',
        businessName: 'Fitness Gear Store',
        vendorName: 'Esther Idoko',
        phoneNumber: '+234 8156789012',
        emailAddress: 'esther@fitnessgear.store',
        businessAddress: '3 Workout Center, Ibadan',
        category: 'Sports',
        dateApplied: '2025-06-15',
        website: 'www.fitnessgearstore.com',
        socialMedia: '@FitnessGearNG (Instagram)',
    },
];
