export const WithdrawalData = [
  {
    transactionId: "WTH1001",
    userName: "John Doe",
    userGroup: "Vendor",
    status: "Pending",
    amount: 12500,
    date: "25/01/27 10:15 AM",
  },
  {
    transactionId: "WTH1002",
    userName: "Salami Ahmed",
    userGroup: "Delivery rep",
    status: "Approved",
    amount: 75000,
    date: "25/01/27 02:45 PM",
  },
  {
    transactionId: "WTH1003",
    userName: "Cynthia Micheal",
    userGroup: "Vendor",
    status: "Pending",
    amount: 8500,
    date: "25/01/27 09:30 AM",
  },
  {
    transactionId: "WTH1004",
    userName: "Chinedu Kalu",
    userGroup: "Vendor",
    status: "Rejected",
    amount: 10000,
    date: "25/01/26 11:10 AM",
  },
  // --- Additional 11 entries starting here ---
  {
    transactionId: "WTH1005",
    userName: "Priscillia Madu",
    userGroup: "Customer",
    status: "Approved",
    amount: 6900,
    date: "25/01/25 04:20 PM",
  },
  {
    transactionId: "WTH1006",
    userName: "Joseph Yemi",
    userGroup: "Delivery rep",
    status: "Approved",
    amount: 15200,
    date: "25/01/25 01:55 PM",
  },
  {
    transactionId: "WTH1007",
    userName: "Aisha Bello",
    userGroup: "Vendor",
    status: "Pending",
    amount: 5000,
    date: "25/01/24 11:00 AM",
  },
  {
    transactionId: "WTH1008",
    userName: "Michael Obi",
    userGroup: "Customer",
    status: "Rejected",
    amount: 2500,
    date: "25/01/23 09:10 AM",
  },
  {
    transactionId: "WTH1009",
    userName: "Jane Smith",
    userGroup: "Vendor",
    status: "Pending",
    amount: 22000,
    date: "25/01/22 03:30 PM",
  },
  {
    transactionId: "WTH1010",
    userName: "David Lee",
    userGroup: "Delivery rep",
    status: "Approved",
    amount: 50000,
    date: "25/01/22 01:00 PM",
  },
  {
    transactionId: "WTH1011",
    userName: "Grace Chin",
    userGroup: "Vendor",
    status: "Pending",
    amount: 18500,
    date: "25/01/21 12:00 PM",
  },
  {
    transactionId: "WTH1012",
    userName: "Victor Okafor",
    userGroup: "Vendor",
    status: "Approved",
    amount: 14000,
    date: "25/01/20 11:00 AM",
  },
  {
    transactionId: "WTH1013",
    userName: "Oluchi Nnaji",
    userGroup: "Customer",
    status: "Rejected",
    amount: 9900,
    date: "25/01/19 10:00 AM",
  },
  {
    transactionId: "WTH1014",
    userName: "Emeka Eze",
    userGroup: "Delivery rep",
    status: "Pending",
    amount: 8700,
    date: "25/01/18 09:00 AM",
  },
  {
    transactionId: "WTH1015",
    userName: "Fatima Ali",
    userGroup: "Vendor",
    status: "Approved",
    amount: 3100,
    date: "25/01/17 08:00 AM",
  },
];


export const TransactionData = [
  {
    transactionId: "WTH1001",
    status: "Pending",
    amount: 12500,
    date: "25/01/27 10:15 AM",
  },
  {
    transactionId: "WTH1002",
    status: "Approved",
    amount: 75000,
    date: "25/01/27 02:45 PM",
  },
  {
    transactionId: "WTH1003",
    status: "Pending",
    amount: 8500,
    date: "25/01/27 09:30 AM",
  },
  {
    transactionId: "WTH1004",
    status: "Rejected",
    amount: 10000,
    date: "25/01/26 11:10 AM",
  },
  {
    transactionId: "WTH1005",
    status: "Approved",
    amount: 6900,
    date: "25/01/25 04:20 PM",
  },
];


export const ApprovalData = [
  {
    submissionId: "AW-1001",
    userName: "John Doe",
    userType: "Vendor",
    bankName: "Zenith Bank",
    accountNumber: "0987654321",
    accountHolderName: "John Doe",
    dateSubmitted: "2025-03-15",
    status: "Pending",
  },
  {
    submissionId: "AW-1002",
    userName: "Jane Smith",
    userType: "Delivery Rep",
    bankName: "GTBank",
    accountNumber: "5678901234",
    accountHolderName: "Jane Smith",
    dateSubmitted: "2025-03-16",
    status: "Pending",
  },
  {
    submissionId: "AW-1003",
    userName: "Ahmed Musa",
    userType: "Vendor",
    bankName: "Access Bank",
    accountNumber: "3456789012",
    accountHolderName: "Ahmed Musa",
    dateSubmitted: "2025-03-17",
    status: "Under Review",
  },
  {
    submissionId: "AW-1004",
    userName: "Chika Okonkwo",
    userType: "Vendor",
    bankName: "First Bank",
    accountNumber: "6789012345",
    accountHolderName: "Chika Okonkwo",
    dateSubmitted: "2025-03-18",
    status: "Pending",
  },
  {
    submissionId: "AW-1005",
    userName: "Samuel Uche",
    userType: "Delivery Rep",
    bankName: "UBA",
    accountNumber: "8901234567",
    accountHolderName: "Samuel Uche",
    dateSubmitted: "2025-03-19",
    status: "Pending",
  },
  {
    submissionId: "AW-1006",
    userName: "Aisha Bello",
    userType: "Vendor",
    bankName: "Fidelity Bank",
    accountNumber: "9012345678",
    accountHolderName: "Aisha Bello",
    dateSubmitted: "2025-03-20",
    status: "Under Review",
  },
  {
    submissionId: "AW-1007",
    userName: "Yusuf Lawal",
    userType: "Delivery Rep",
    bankName: "Polaris Bank",
    accountNumber: "2345678901",
    accountHolderName: "Yusuf Lawal",
    dateSubmitted: "2025-03-21",
    status: "Pending",
  },
  {
    submissionId: "AW-1008",
    userName: "Adeola Adebayo",
    userType: "Vendor",
    bankName: "Ecobank",
    accountNumber: "8765432109",
    accountHolderName: "Adeola Adebayo",
    dateSubmitted: "2025-03-22",
    status: "Pending",
  },
  {
    submissionId: "AW-1009",
    userName: "Ibrahim Abubakar",
    userType: "Vendor",
    bankName: "Sterling Bank",
    accountNumber: "7654321098",
    accountHolderName: "Ibrahim Abubakar",
    dateSubmitted: "2025-03-23",
    status: "Under Review",
  },
  {
    submissionId: "AW-1010",
    userName: "Funke Adewale",
    userType: "Delivery Rep",
    bankName: "Wema Bank",
    accountNumber: "6543210987",
    accountHolderName: "Funke Adewale",
    dateSubmitted: "2025-03-24",
    status: "Pending",
  },
  {
    submissionId: "AW-1011",
    userName: "Emeka Nwosu",
    userType: "Vendor",
    bankName: "Unity Bank",
    accountNumber: "5432109876",
    accountHolderName: "Emeka Nwosu",
    dateSubmitted: "2025-03-25",
    status: "Pending",
  },
  {
    submissionId: "AW-1012",
    userName: "Mary Ojo",
    userType: "Vendor",
    bankName: "Kuda Bank",
    accountNumber: "4321098765",
    accountHolderName: "Mary Ojo",
    dateSubmitted: "2025-03-26",
    status: "Under Review",
  },
  {
    submissionId: "AW-1013",
    userName: "Peter Obi",
    userType: "Vendor",
    bankName: "Opay",
    accountNumber: "3210987654",
    accountHolderName: "Peter Obi",
    dateSubmitted: "2025-03-27",
    status: "Pending",
  },
];
export const users = [
  {
    id: "AW-1001",
    userName: "John Doe",
    userType: "Vendor",
    businessName: "Doe Logistics",
    bankName: "Zenith Bank",
    accountNumber: "1234567890",
    accountHolderName: "John Doe",
    bvn: "223344556677",
    dateSubmitted: "2025-03-15",
    previousTransactions: "Yes (View Transactions)",
    autoVerificationStatus: "Passed",
    adminNotes: "BVN match confirmed.",
    status: "Pending",
  },
  {
    id: "AW-1002",
    userName: "Jane Smith",
    userType: "Delivery Rep", // Changed to Delivery Rep for variety
    businessName: "Smith Transport",
    bankName: "First Bank",
    accountNumber: "9876543210",
    accountHolderName: "Jane Smith",
    bvn: "998877665544",
    dateSubmitted: "2025-03-20",
    previousTransactions: "No",
    autoVerificationStatus: "Pending",
    adminNotes: "Awaiting manual document review.",
    status: "Pending",
  },
  {
    id: "AW-1003",
    userName: "Emeka Nwosu",
    userType: "Vendor",
    businessName: "Emeka's Electronics",
    bankName: "GTBank",
    accountNumber: "5544332211",
    accountHolderName: "Emeka Nwosu",
    bvn: "112233445566",
    dateSubmitted: "2025-03-25",
    previousTransactions: "Yes (View Transactions)",
    autoVerificationStatus: "Failed",
    adminNotes: "Account name mismatch.",
    status: "Rejected", // Example of a rejected user
  },
  {
    id: "AW-1004",
    userName: "Aisha Bello",
    userType: "Vendor",
    businessName: "Aisha Trading Co.",
    bankName: "Access Bank",
    accountNumber: "1029384756",
    accountHolderName: "Aisha Bello",
    bvn: "776655443322",
    dateSubmitted: "2025-03-28",
    previousTransactions: "No",
    autoVerificationStatus: "Passed",
    adminNotes: "Ready for approval.",
    status: "Approved", // Example of an approved user
  },
  {
    id: "AW-1005",
    userName: "Chinedu Okoro",
    userType: "Delivery Rep",
    businessName: "Quick Delivery",
    bankName: "UBA",
    accountNumber: "6677889900",
    accountHolderName: "Chinedu Okoro",
    bvn: "445566778899",
    dateSubmitted: "2025-04-01",
    previousTransactions: "No",
    autoVerificationStatus: "Pending",
    adminNotes: "",
    status: "Pending",
  },
  {
    id: "AW-1006",
    userName: "Fatima Lawal",
    userType: "Vendor",
    businessName: "Lawal Farms",
    bankName: "Fidelity Bank",
    accountNumber: "1122334455",
    accountHolderName: "Fatima Lawal",
    bvn: "001122334455",
    dateSubmitted: "2025-04-03",
    previousTransactions: "Yes (View Transactions)",
    autoVerificationStatus: "Passed",
    adminNotes: "Requires director sign-off.",
    status: "Pending",
  },
  {
    id: "AW-1007",
    userName: "Kunle Adebayo",
    userType: "Delivery Rep",
    businessName: "Kunle Riders",
    bankName: "Wema Bank",
    accountNumber: "9900112233",
    accountHolderName: "Kunle Adebayo",
    bvn: "887766554433",
    dateSubmitted: "2025-04-05",
    previousTransactions: "No",
    autoVerificationStatus: "Failed",
    adminNotes: "Invalid BVN format.",
    status: "Rejected",
  },
  {
    id: "AW-1008",
    userName: "Sarah Obi",
    userType: "Vendor",
    businessName: "Obi Consults",
    bankName: "Stanbic IBTC",
    accountNumber: "4567890123",
    accountHolderName: "Sarah Obi",
    bvn: "334455667788",
    dateSubmitted: "2025-04-08",
    previousTransactions: "Yes (View Transactions)",
    autoVerificationStatus: "Passed",
    adminNotes: "Approved by Admin 1.",
    status: "Approved",
  },
  {
    id: "AW-1009",
    userName: "Godwin Efe",
    userType: "Delivery Rep",
    businessName: "Efe Logistics",
    bankName: "Ecobank",
    accountNumber: "7788990011",
    accountHolderName: "Godwin Efe",
    bvn: "123123123123",
    dateSubmitted: "2025-04-10",
    previousTransactions: "No",
    autoVerificationStatus: "Pending",
    adminNotes: "Awaiting ID verification.",
    status: "Pending",
  },
  {
    id: "AW-1010",
    userName: "Tunde Oladipo",
    userType: "Vendor",
    businessName: "Oladipo Services",
    bankName: "Zenith Bank",
    accountNumber: "0011223344",
    accountHolderName: "Tunde Oladipo",
    bvn: "909090909090",
    dateSubmitted: "2025-04-12",
    previousTransactions: "Yes (View Transactions)",
    autoVerificationStatus: "Passed",
    adminNotes: "",
    status: "Pending",
  },
  {
    id: "AW-1011",
    userName: "Amaka Eze",
    userType: "Delivery Rep",
    businessName: "Eze Transport",
    bankName: "First Bank",
    accountNumber: "3344556677",
    accountHolderName: "Amaka Eze",
    bvn: "135792468012",
    dateSubmitted: "2025-04-15",
    previousTransactions: "No",
    autoVerificationStatus: "Failed",
    adminNotes: "Address verification failed.",
    status: "Rejected",
  },
  {
    id: "AW-1012",
    userName: "Usman Ali",
    userType: "Vendor",
    businessName: "Ali Foods",
    bankName: "GTBank",
    accountNumber: "7766554433",
    accountHolderName: "Usman Ali",
    bvn: "246801357913",
    dateSubmitted: "2025-04-18",
    previousTransactions: "Yes (View Transactions)",
    autoVerificationStatus: "Passed",
    adminNotes: "Approved by Compliance Team.",
    status: "Approved",
  },
  {
    id: "AW-1013",
    userName: "Mercy Johnson",
    userType: "Delivery Rep",
    businessName: "Mercy Courier",
    bankName: "Access Bank",
    accountNumber: "2233445566",
    accountHolderName: "Mercy Johnson",
    bvn: "975318642019",
    dateSubmitted: "2025-04-21",
    previousTransactions: "No",
    autoVerificationStatus: "Pending",
    adminNotes: "New registration, priority review.",
    status: "Pending",
  },
  {
    id: "AW-1014",
    userName: "Segun Obafemi",
    userType: "Vendor",
    businessName: "Segun Imports",
    bankName: "Union Bank",
    accountNumber: "8899001122",
    accountHolderName: "Segun Obafemi",
    bvn: "111222333444",
    dateSubmitted: "2025-04-24",
    previousTransactions: "Yes (View Transactions)",
    autoVerificationStatus: "Passed",
    adminNotes: "All documents confirmed.",
    status: "Pending",
  },
];